'use client';

import Typography from '@mui/material/Typography';
import CompareStatistic from '@/components/generic/CompareStatistic';
import { useAppSelector } from '@/redux/hooks';
import { Skeleton } from '@mui/material';
import PredictionLine from './PredictionLine';
import CBB from '@/components/helpers/CBB';
import Organization from '@/components/helpers/Organization';
import CFB from '@/components/helpers/CFB';
import React from 'react';


/**
* Get the loading skeletons for the picks stats
*/
export const getSkeleton = (numberOfSkeletons: number): React.JSX.Element[] => {
  const skeletons: React.JSX.Element[] = [];

  for (let i = 0; i < numberOfSkeletons; i++) {
    skeletons.push(<Skeleton key = {i} variant="text" animation="wave" sx = {{
      width: '100%', maxWidth, height: '30px', margin: '10px auto',
    }} />);
  }

  return skeletons;
};

export const maxWidth = 600;

export const getSections = ({ homeStats, awayStats }) => {
  // Ones up here are shared by both CBB and CFB (for now)
  const overviewRows = [
    {
      name: 'Record',
      title: 'Record',
      away: `${awayStats.wins || 0}-${awayStats.losses || 0}`,
      home: `${homeStats.wins || 0}-${homeStats.losses || 0}`,
      awayCompareValue: awayStats.wins,
      homeCompareValue: homeStats.wins,
      favored: 'higher',
      showDifference: true,
      precision: 0,
    },
    {
      name: 'Conf',
      title: 'Conference record',
      away: `${awayStats.confwins || 0}-${awayStats.conflosses || 0}`,
      home: `${homeStats.confwins || 0}-${homeStats.conflosses || 0}`,
      awayCompareValue: awayStats.confwins,
      homeCompareValue: homeStats.confwins,
      favored: 'higher',
      showDifference: true,
      precision: 0,
    },
    {
      name: 'Streak',
      title: 'Streak',
      away: 'streak' in awayStats ? ((awayStats.streak < 0 ? 'L' : 'W') + Math.abs(awayStats.streak)) : '0',
      home: 'streak' in homeStats ? ((homeStats.streak < 0 ? 'L' : 'W') + Math.abs(homeStats.streak)) : '0',
      awayCompareValue: awayStats.streak,
      homeCompareValue: homeStats.streak,
      favored: 'higher',
    },
    {
      name: 'A/H Rec.',
      title: 'Away record / Home record',
      away: `${awayStats.roadwins || 0}-${awayStats.roadlosses || 0}`,
      home: `${homeStats.homewins || 0}-${homeStats.homelosses || 0}`,
      awayCompareValue: awayStats.roadlosses,
      homeCompareValue: homeStats.homelosses,
      favored: 'lower',
      showDifference: true,
      precision: 0,
    },
  ];

  const marginRows = [
    {
      name: 'Win MR',
      title: 'Avg. Win margin',
      away: awayStats.win_margin,
      home: homeStats.win_margin,
      awayCompareValue: awayStats.win_margin,
      homeCompareValue: homeStats.win_margin,
      favored: 'higher',
      showDifference: true,
    },
    {
      name: 'Loss MR',
      title: 'Avg. Loss margin',
      away: awayStats.loss_margin,
      home: homeStats.loss_margin,
      awayCompareValue: awayStats.loss_margin,
      homeCompareValue: homeStats.loss_margin,
      favored: 'lower',
      showDifference: true,
    },
    {
      name: 'Conf. W MR',
      title: 'Avg. Conference win margin',
      away: awayStats.confwin_margin,
      home: homeStats.confwin_margin,
      awayCompareValue: awayStats.confwin_margin,
      homeCompareValue: homeStats.confwin_margin,
      favored: 'higher',
      showDifference: true,
    },
    {
      name: 'Conf. L MR',
      title: 'Avg. Conference loss margin',
      away: awayStats.confloss_margin,
      home: homeStats.confloss_margin,
      awayCompareValue: awayStats.confloss_margin,
      homeCompareValue: homeStats.confloss_margin,
      favored: 'lower',
      showDifference: true,
    },
  ];


  if (Organization.isCFB()) {
    return [
      {
        name: 'Record',
        rows: overviewRows,
      },
      {
        name: 'Rank',
        rows: [
          {
            name: 'Rank',
            title: 'sRating rank',
            away: awayStats.rank || '-',
            home: homeStats.rank || '-',
            awayCompareValue: awayStats.rank || Infinity,
            homeCompareValue: homeStats.rank || Infinity,
            favored: 'lower',
            showDifference: true,
            precision: 0,
          },
          {
            name: 'sRating elo',
            title: 'sRating elo',
            away: awayStats.elo,
            home: homeStats.elo,
            awayCompareValue: awayStats.elo,
            homeCompareValue: homeStats.elo,
            awayRank: awayStats.elo_rank,
            homeRank: homeStats.elo_rank,
            favored: 'higher',
            showDifference: true,
            precision: 0,
          },
        ],
      },
      {
        name: 'Efficiency',
        rows: [
          {
            name: 'QBR(c)',
            title: 'Quarterback rating (college)',
            away: awayStats.passing_rating_college,
            home: homeStats.passing_rating_college,
            awayCompareValue: awayStats.passing_rating_college,
            homeCompareValue: homeStats.passing_rating_college,
            awayRank: awayStats.passing_rating_college_rank,
            homeRank: homeStats.passing_rating_college_rank,
            favored: 'higher',
            showDifference: true,
            compareType: 'rank',
          },
          {
            name: 'YPP',
            title: 'Yards per play',
            away: awayStats.yards_per_play,
            home: homeStats.yards_per_play,
            awayCompareValue: awayStats.yards_per_play,
            homeCompareValue: homeStats.yards_per_play,
            awayRank: awayStats.yards_per_play_rank,
            homeRank: homeStats.yards_per_play_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'PPP',
            title: 'Points per play',
            away: awayStats.points_per_play,
            home: homeStats.points_per_play,
            awayCompareValue: awayStats.points_per_play,
            homeCompareValue: homeStats.points_per_play,
            awayRank: awayStats.points_per_play_rank,
            homeRank: homeStats.points_per_play_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'PTS Off.',
            title: 'Avg points scored',
            away: awayStats.points,
            home: homeStats.points,
            awayCompareValue: awayStats.points,
            homeCompareValue: homeStats.points,
            awayRank: awayStats.points_rank,
            homeRank: homeStats.points_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'PTS Def.',
            title: 'Avg points allowed',
            away: awayStats.opponent_points,
            home: homeStats.opponent_points,
            awayCompareValue: awayStats.opponent_points,
            homeCompareValue: homeStats.opponent_points,
            awayRank: awayStats.opponent_points_rank,
            homeRank: homeStats.opponent_points_rank,
            favored: 'lower',
            showDifference: true,
          },
          // {
          //   name: 'D-DVOA',
          //   title: 'Defensive DVOA',
          //   value: teamStats.defensive_dvoa,
          //   rank: teamStats.defensive_dvoa_rank,
          // },
          // {
          //   name: 'O-DVOA',
          //   title: 'Offensive DVOA',
          //   value: teamStats.offensive_dvoa,
          //   rank: teamStats.offensive_dvoa_rank,
          // },
        ],
      },
      {
        name: 'Passing',
        rows: [
          {
            name: 'Att.',
            title: 'Attempts',
            away: awayStats.passing_attempts,
            home: homeStats.passing_attempts,
            awayCompareValue: awayStats.passing_attempts,
            homeCompareValue: homeStats.passing_attempts,
            awayRank: awayStats.passing_attempts_rank,
            homeRank: homeStats.passing_attempts_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Comp.',
            title: 'Completions',
            away: awayStats.passing_completions,
            home: homeStats.passing_completions,
            awayCompareValue: awayStats.passing_completions,
            homeCompareValue: homeStats.passing_completions,
            awayRank: awayStats.passing_completions_rank,
            homeRank: homeStats.passing_completions_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Yards',
            title: 'Yards',
            away: awayStats.passing_yards,
            home: homeStats.passing_yards,
            awayCompareValue: awayStats.passing_yards,
            homeCompareValue: homeStats.passing_yards,
            awayRank: awayStats.passing_yards_rank,
            homeRank: homeStats.passing_yards_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Comp. %',
            title: 'Completion %',
            away: awayStats.passing_completion_percentage,
            home: homeStats.passing_completion_percentage,
            awayCompareValue: awayStats.passing_completion_percentage,
            homeCompareValue: homeStats.passing_completion_percentage,
            awayRank: awayStats.passing_completion_percentage_rank,
            homeRank: homeStats.passing_completion_percentage_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Yds per att.',
            title: 'Yards per attempt',
            away: awayStats.passing_yards_per_attempt,
            home: homeStats.passing_yards_per_attempt,
            awayCompareValue: awayStats.passing_yards_per_attempt,
            homeCompareValue: homeStats.passing_yards_per_attempt,
            awayRank: awayStats.passing_yards_per_attempt_rank,
            homeRank: homeStats.passing_yards_per_attempt_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Yds per comp.',
            title: 'Yards per completion',
            away: awayStats.passing_yards_per_completion,
            home: homeStats.passing_yards_per_completion,
            awayCompareValue: awayStats.passing_yards_per_completion,
            homeCompareValue: homeStats.passing_yards_per_completion,
            awayRank: awayStats.passing_yards_per_completion_rank,
            homeRank: homeStats.passing_yards_per_completion_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'TDs',
            title: 'Touchdowns',
            away: awayStats.passing_touchdowns,
            home: homeStats.passing_touchdowns,
            awayCompareValue: awayStats.passing_touchdowns,
            homeCompareValue: homeStats.passing_touchdowns,
            awayRank: awayStats.passing_touchdowns_rank,
            homeRank: homeStats.passing_touchdowns_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Int.',
            title: 'Interceptions',
            away: awayStats.passing_interceptions,
            home: homeStats.passing_interceptions,
            awayCompareValue: awayStats.passing_interceptions,
            homeCompareValue: homeStats.passing_interceptions,
            awayRank: awayStats.passing_interceptions_rank,
            homeRank: homeStats.passing_interceptions_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Long',
            title: 'Long',
            away: awayStats.passing_long,
            home: homeStats.passing_long,
            awayCompareValue: awayStats.passing_long,
            homeCompareValue: homeStats.passing_long,
            awayRank: awayStats.passing_long_rank,
            homeRank: homeStats.passing_long_rank,
            favored: 'higher',
            showDifference: true,
          },
        ],
      },
      {
        name: 'Rushing',
        rows: [
          {
            name: 'Att.',
            title: 'Attempts',
            away: awayStats.rushing_attempts,
            home: homeStats.rushing_attempts,
            awayCompareValue: awayStats.rushing_attempts,
            homeCompareValue: homeStats.rushing_attempts,
            awayRank: awayStats.rushing_attempts_rank,
            homeRank: homeStats.rushing_attempts_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Yds',
            title: 'Yards',
            away: awayStats.rushing_yards,
            home: homeStats.rushing_yards,
            awayCompareValue: awayStats.rushing_yards,
            homeCompareValue: homeStats.rushing_yards,
            awayRank: awayStats.rushing_yards_rank,
            homeRank: homeStats.rushing_yards_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Yds per att.',
            title: 'Yards per attempt',
            away: awayStats.rushing_yards_per_attempt,
            home: homeStats.rushing_yards_per_attempt,
            awayCompareValue: awayStats.rushing_yards_per_attempt,
            homeCompareValue: homeStats.rushing_yards_per_attempt,
            awayRank: awayStats.rushing_yards_per_attempt_rank,
            homeRank: homeStats.rushing_yards_per_attempt_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'TDs',
            title: 'Touchdowns',
            away: awayStats.rushing_touchdowns,
            home: homeStats.rushing_touchdowns,
            awayCompareValue: awayStats.rushing_touchdowns,
            homeCompareValue: homeStats.rushing_touchdowns,
            awayRank: awayStats.rushing_touchdowns_rank,
            homeRank: homeStats.rushing_touchdowns_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Long',
            title: 'Long',
            away: awayStats.rushing_long,
            home: homeStats.rushing_long,
            awayCompareValue: awayStats.rushing_long,
            homeCompareValue: homeStats.rushing_long,
            awayRank: awayStats.rushing_long_rank,
            homeRank: homeStats.rushing_long_rank,
            favored: 'higher',
            showDifference: true,
          },
        ],
      },
      /*
      {
        name: 'Receiving',
        rows: [
          {
            name: 'Recep.',
            title: 'Receptions',
            away: awayStats.receptions,
            home: homeStats.receptions,
            awayCompareValue: awayStats.receptions,
            homeCompareValue: homeStats.receptions,
            awayRank: awayStats.receptions_rank,
            homeRank: homeStats.receptions_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Yds',
            title: 'Yards',
            away: awayStats.receiving_yards,
            home: homeStats.receiving_yards,
            awayCompareValue: awayStats.receiving_yards,
            homeCompareValue: homeStats.receiving_yards,
            awayRank: awayStats.receiving_yards_rank,
            homeRank: homeStats.receiving_yards_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Yds per recep.',
            title: 'Yards per reception',
            away: awayStats.receiving_yards_per_reception,
            home: homeStats.receiving_yards_per_reception,
            awayCompareValue: awayStats.receiving_yards_per_reception,
            homeCompareValue: homeStats.receiving_yards_per_reception,
            awayRank: awayStats.receiving_yards_per_reception_rank,
            homeRank: homeStats.receiving_yards_per_reception_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'TDs',
            title: 'Touchdowns',
            away: awayStats.receiving_touchdowns,
            home: homeStats.receiving_touchdowns,
            awayCompareValue: awayStats.receiving_touchdowns,
            homeCompareValue: homeStats.receiving_touchdowns,
            awayRank: awayStats.receiving_touchdowns_rank,
            homeRank: homeStats.receiving_touchdowns_rank,
            favored: 'higher',
            showDifference: true,
          },
          {
            name: 'Long',
            title: 'Long',
            away: awayStats.receiving_long,
            home: homeStats.receiving_long,
            awayCompareValue: awayStats.receiving_long,
            homeCompareValue: homeStats.receiving_long,
            awayRank: awayStats.receiving_long_rank,
            homeRank: homeStats.receiving_long_rank,
            favored: 'higher',
            showDifference: true,
          },
        ],
      },
      */
      {
        name: 'Margin',
        rows: marginRows,
      },
      {
        name: 'Defensive',
        rows: [
          {
            name: 'Opp. PTS',
            title: 'Opponent points',
            away: awayStats.opponent_points,
            home: homeStats.opponent_points,
            awayCompareValue: awayStats.opponent_points,
            homeCompareValue: homeStats.opponent_points,
            awayRank: awayStats.opponent_points_rank,
            homeRank: homeStats.opponent_points_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. YPP',
            title: 'Opponent Yards per play',
            away: awayStats.opponent_yards_per_play,
            home: homeStats.opponent_yards_per_play,
            awayCompareValue: awayStats.opponent_yards_per_play,
            homeCompareValue: homeStats.opponent_yards_per_play,
            awayRank: awayStats.opponent_yards_per_play_rank,
            homeRank: homeStats.opponent_yards_per_play_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. PPP',
            title: 'Opponent Points per play',
            away: awayStats.opponent_points_per_play,
            home: homeStats.opponent_points_per_play,
            awayCompareValue: awayStats.opponent_points_per_play,
            homeCompareValue: homeStats.opponent_points_per_play,
            awayRank: awayStats.opponent_points_per_play_rank,
            homeRank: homeStats.opponent_points_per_play_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Pass att.',
            title: 'Opponent Passing attempts',
            away: awayStats.opponent_passing_attempts,
            home: homeStats.opponent_passing_attempts,
            awayCompareValue: awayStats.opponent_passing_attempts,
            homeCompareValue: homeStats.opponent_passing_attempts,
            awayRank: awayStats.opponent_passing_attempts_rank,
            homeRank: homeStats.opponent_passing_attempts_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Pass comp.',
            title: 'Opponent Passing completions',
            away: awayStats.opponent_passing_completions,
            home: homeStats.opponent_passing_completions,
            awayCompareValue: awayStats.opponent_passing_completions,
            homeCompareValue: homeStats.opponent_passing_completions,
            awayRank: awayStats.opponent_passing_completions_rank,
            homeRank: homeStats.opponent_passing_completions_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Pass yds',
            title: 'Opponent Passing yards',
            away: awayStats.opponent_passing_yards,
            home: homeStats.opponent_passing_yards,
            awayCompareValue: awayStats.opponent_passing_yards,
            homeCompareValue: homeStats.opponent_passing_yards,
            awayRank: awayStats.opponent_passing_yards_rank,
            homeRank: homeStats.opponent_passing_yards_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Pass comp. %',
            title: 'Opponent Passing completions percentage',
            away: awayStats.opponent_passing_completion_percentage,
            home: homeStats.opponent_passing_completion_percentage,
            awayCompareValue: awayStats.opponent_passing_completion_percentage,
            homeCompareValue: homeStats.opponent_passing_completion_percentage,
            awayRank: awayStats.opponent_passing_completion_percentage_rank,
            homeRank: homeStats.opponent_passing_completion_percentage_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Pass yds per att.',
            title: 'Opponent Passing yard per attempt',
            away: awayStats.opponent_passing_yards_per_attempt,
            home: homeStats.opponent_passing_yards_per_attempt,
            awayCompareValue: awayStats.opponent_passing_yards_per_attempt,
            homeCompareValue: homeStats.opponent_passing_yards_per_attempt,
            awayRank: awayStats.opponent_passing_yards_per_attempt_rank,
            homeRank: homeStats.opponent_passing_yards_per_attempt_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Pass yds per comp.',
            title: 'Opponent Passing yards per completion',
            away: awayStats.opponent_passing_yards_per_completion,
            home: homeStats.opponent_passing_yards_per_completion,
            awayCompareValue: awayStats.opponent_passing_yards_per_completion,
            homeCompareValue: homeStats.opponent_passing_yards_per_completion,
            awayRank: awayStats.opponent_passing_yards_per_completion_rank,
            homeRank: homeStats.opponent_passing_yards_per_completion_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Pass TD',
            title: 'Opponent Passing touchdowns',
            away: awayStats.opponent_passing_touchdowns,
            home: homeStats.opponent_passing_touchdowns,
            awayCompareValue: awayStats.opponent_passing_touchdowns,
            homeCompareValue: homeStats.opponent_passing_touchdowns,
            awayRank: awayStats.opponent_passing_touchdowns_rank,
            homeRank: homeStats.opponent_passing_touchdowns_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Pass int.',
            title: 'Opponent Passing interceptions',
            away: awayStats.opponent_passing_interceptions,
            home: homeStats.opponent_passing_interceptions,
            awayCompareValue: awayStats.opponent_passing_interceptions,
            homeCompareValue: homeStats.opponent_passing_interceptions,
            awayRank: awayStats.opponent_passing_interceptions_rank,
            homeRank: homeStats.opponent_passing_interceptions_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Pass long',
            title: 'Opponent Passing long',
            away: awayStats.opponent_passing_long,
            home: homeStats.opponent_passing_long,
            awayCompareValue: awayStats.opponent_passing_long,
            homeCompareValue: homeStats.opponent_passing_long,
            awayRank: awayStats.opponent_passing_long_rank,
            homeRank: homeStats.opponent_passing_long_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Rush att.',
            title: 'Opponent Rushing attempts',
            away: awayStats.opponent_rushing_attempts,
            home: homeStats.opponent_rushing_attempts,
            awayCompareValue: awayStats.opponent_rushing_attempts,
            homeCompareValue: homeStats.opponent_rushing_attempts,
            awayRank: awayStats.opponent_rushing_attempts_rank,
            homeRank: homeStats.opponent_rushing_attempts_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Rush yds',
            title: 'Opponent Rushing yards',
            away: awayStats.opponent_rushing_yards,
            home: homeStats.opponent_rushing_yards,
            awayCompareValue: awayStats.opponent_rushing_yards,
            homeCompareValue: homeStats.opponent_rushing_yards,
            awayRank: awayStats.opponent_rushing_yards_rank,
            homeRank: homeStats.opponent_rushing_yards_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Rush yds per att.',
            title: 'Opponent Rushing yards per attempt',
            away: awayStats.opponent_rushing_yards_per_attempt,
            home: homeStats.opponent_rushing_yards_per_attempt,
            awayCompareValue: awayStats.opponent_rushing_yards_per_attempt,
            homeCompareValue: homeStats.opponent_rushing_yards_per_attempt,
            awayRank: awayStats.opponent_rushing_yards_per_attempt_rank,
            homeRank: homeStats.opponent_rushing_yards_per_attempt_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Rush TD',
            title: 'Opponent Rushing touchdowns',
            away: awayStats.opponent_rushing_touchdowns,
            home: homeStats.opponent_rushing_touchdowns,
            awayCompareValue: awayStats.opponent_rushing_touchdowns,
            homeCompareValue: homeStats.opponent_rushing_touchdowns,
            awayRank: awayStats.opponent_rushing_touchdowns_rank,
            homeRank: homeStats.opponent_rushing_touchdowns_rank,
            favored: 'lower',
            showDifference: true,
          },
          {
            name: 'Opp. Rush long',
            title: 'Opponent Rushing long',
            away: awayStats.opponent_rushing_long,
            home: homeStats.opponent_rushing_long,
            awayCompareValue: awayStats.opponent_rushing_long,
            homeCompareValue: homeStats.opponent_rushing_long,
            awayRank: awayStats.opponent_rushing_long_rank,
            homeRank: homeStats.opponent_rushing_long_rank,
            favored: 'lower',
            showDifference: true,
          },
          // {
          //   name: 'Opp. Recep.',
          //   title: 'Opponent # of receptions',
          //   away: awayStats.opponent_receptions,
          //   home: homeStats.opponent_receptions,
          //   awayCompareValue: awayStats.opponent_receptions,
          //   homeCompareValue: homeStats.opponent_receptions,
          //   awayRank: awayStats.opponent_receptions_rank,
          //   homeRank: homeStats.opponent_receptions_rank,
          //   favored: 'lower',
          //   showDifference: true,
          // },
          // {
          //   name: 'Opp. Rec. yds',
          //   title: 'Opponent Receiving yards',
          //   away: awayStats.opponent_receiving_yards,
          //   home: homeStats.opponent_receiving_yards,
          //   awayCompareValue: awayStats.opponent_receiving_yards,
          //   homeCompareValue: homeStats.opponent_receiving_yards,
          //   awayRank: awayStats.opponent_receiving_yards_rank,
          //   homeRank: homeStats.opponent_receiving_yards_rank,
          //   favored: 'lower',
          //   showDifference: true,
          // },
          // {
          //   name: 'Opp. Rec. yds per recep.',
          //   title: 'Opponent Receiving yards per reception',
          //   away: awayStats.opponent_receiving_yards_per_reception,
          //   home: homeStats.opponent_receiving_yards_per_reception,
          //   awayCompareValue: awayStats.opponent_receiving_yards_per_reception,
          //   homeCompareValue: homeStats.opponent_receiving_yards_per_reception,
          //   awayRank: awayStats.opponent_receiving_yards_per_reception_rank,
          //   homeRank: homeStats.opponent_receiving_yards_per_reception_rank,
          //   favored: 'lower',
          //   showDifference: true,
          // },
          // {
          //   name: 'Opp. Rec. TD',
          //   title: 'Opponent Receiving touchdowns',
          //   away: awayStats.opponent_receiving_touchdowns,
          //   home: homeStats.opponent_receiving_touchdowns,
          //   awayCompareValue: awayStats.opponent_receiving_touchdowns,
          //   homeCompareValue: homeStats.opponent_receiving_touchdowns,
          //   awayRank: awayStats.opponent_receiving_touchdowns_rank,
          //   homeRank: homeStats.opponent_receiving_touchdowns_rank,
          //   favored: 'lower',
          //   showDifference: true,
          // },
          // {
          //   name: 'Opp. Rec. long',
          //   title: 'Opponent Receiving long',
          //   away: awayStats.opponent_receiving_long,
          //   home: homeStats.opponent_receiving_long,
          //   awayCompareValue: awayStats.opponent_receiving_long,
          //   homeCompareValue: homeStats.opponent_receiving_long,
          //   awayRank: awayStats.opponent_receiving_long_rank,
          //   homeRank: homeStats.opponent_receiving_long_rank,
          //   favored: 'lower',
          //   showDifference: true,
          // },
        ],
      },
    ];
  }

  // defaulting to CBB
  return [
    {
      name: 'Record',
      rows: overviewRows,
    },
    {
      name: 'Efficiency',
      rows: [
        {
          name: 'aEM',
          title: 'Adjusted Efficiency margin',
          away: awayStats.adjusted_efficiency_rating,
          home: homeStats.adjusted_efficiency_rating,
          awayCompareValue: awayStats.adjusted_efficiency_rating,
          homeCompareValue: homeStats.adjusted_efficiency_rating,
          awayRank: awayStats.adjusted_efficiency_rating_rank,
          homeRank: homeStats.adjusted_efficiency_rating_rank,
          favored: 'higher',
          showDifference: true,
          compareType: 'rank',
        },
        {
          name: 'aSOS',
          title: 'aSOS',
          tooltip: 'Adj efficiency Strength of Schedule',
          away: awayStats.opponent_efficiency_rating,
          home: homeStats.opponent_efficiency_rating,
          awayCompareValue: awayStats.opponent_efficiency_rating,
          homeCompareValue: homeStats.opponent_efficiency_rating,
          awayRank: awayStats.opponent_efficiency_rating_rank,
          homeRank: homeStats.opponent_efficiency_rating_rank,
          favored: 'higher',
          showDifference: true,
          compareType: 'rank',
        },
        {
          name: 'eSOS',
          title: 'eSOS',
          tooltip: 'SR (elo) Strength of Schedule',
          away: awayStats.elo_sos,
          home: homeStats.elo_sos,
          awayCompareValue: awayStats.elo_sos,
          homeCompareValue: homeStats.elo_sos,
          awayRank: awayStats.elo_sos_rank,
          homeRank: homeStats.elo_sos_rank,
          favored: 'higher',
          showDifference: true,
          compareType: 'rank',
        },
        {
          name: 'ORT',
          title: 'Offensive rating',
          away: awayStats.offensive_rating,
          home: homeStats.offensive_rating,
          awayCompareValue: awayStats.offensive_rating,
          homeCompareValue: homeStats.offensive_rating,
          awayRank: awayStats.offensive_rating_rank,
          homeRank: homeStats.offensive_rating_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'DRT',
          title: 'Defensive rating',
          away: awayStats.defensive_rating,
          home: homeStats.defensive_rating,
          awayCompareValue: awayStats.defensive_rating,
          homeCompareValue: homeStats.defensive_rating,
          awayRank: awayStats.defensive_rating_rank,
          homeRank: homeStats.defensive_rating_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'PTS Off.',
          title: 'Avg points scored',
          away: awayStats.points,
          home: homeStats.points,
          awayCompareValue: awayStats.points,
          homeCompareValue: homeStats.points,
          awayRank: awayStats.points_rank,
          homeRank: homeStats.points_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'PTS Def.',
          title: 'Avg points allowed',
          away: awayStats.opponent_points,
          home: homeStats.opponent_points,
          awayCompareValue: awayStats.opponent_points,
          homeCompareValue: homeStats.opponent_points,
          awayRank: awayStats.opponent_points_rank,
          homeRank: homeStats.opponent_points_rank,
          favored: 'lower',
          showDifference: true,
        },
      ],
    },
    {
      name: 'Rank',
      rows: [
        {
          name: 'Rank',
          title: 'sRating rank',
          away: awayStats.rank || '-',
          home: homeStats.rank || '-',
          awayCompareValue: awayStats.rank || Infinity,
          homeCompareValue: homeStats.rank || Infinity,
          favored: 'lower',
          showDifference: true,
          precision: 0,
        },
        {
          name: 'sRating elo',
          title: 'sRating elo',
          away: awayStats.elo,
          home: homeStats.elo,
          awayCompareValue: awayStats.elo,
          homeCompareValue: homeStats.elo,
          awayRank: awayStats.elo_rank,
          homeRank: homeStats.elo_rank,
          favored: 'higher',
          showDifference: true,
          precision: 0,
        },
        {
          name: 'NET',
          title: 'NET',
          away: awayStats.net_rank || '-',
          home: homeStats.net_rank || '-',
          awayCompareValue: awayStats.net_rank || Infinity,
          homeCompareValue: homeStats.net_rank || Infinity,
          favored: 'lower',
          showDifference: true,
          precision: 0,
        },
        {
          name: 'KP',
          title: 'Kenpom',
          away: awayStats.kenpom_rank || '-',
          home: homeStats.kenpom_rank || '-',
          awayCompareValue: awayStats.kenpom_rank || Infinity,
          homeCompareValue: homeStats.kenpom_rank || Infinity,
          favored: 'lower',
          showDifference: true,
          precision: 0,
        },
        {
          name: 'SRS',
          title: 'SRS',
          away: awayStats.srs_rank || '-',
          home: homeStats.srs_rank || '-',
          awayCompareValue: awayStats.srs_rank || Infinity,
          homeCompareValue: homeStats.srs_rank || Infinity,
          favored: 'lower',
          showDifference: true,
          precision: 0,
        },
        {
          name: 'AP',
          title: 'AP',
          away: awayStats.ap_rank || '-',
          home: homeStats.ap_rank || '-',
          awayCompareValue: awayStats.ap_rank || Infinity,
          homeCompareValue: homeStats.ap_rank || Infinity,
          favored: 'lower',
          showDifference: true,
          precision: 0,
        },
        {
          name: 'Coaches',
          title: 'Coaches Poll',
          away: awayStats.coaches_rank || '-',
          home: homeStats.coaches_rank || '-',
          awayCompareValue: awayStats.coaches_rank || Infinity,
          homeCompareValue: homeStats.coaches_rank || Infinity,
          favored: 'lower',
          showDifference: true,
          precision: 0,
        },
      ],
    },
    {
      name: 'Margin',
      rows: marginRows,
    },
    {
      name: 'Offense',
      rows: [
        {
          name: 'Pace',
          title: 'Pace',
          tooltip: 'Possesions per game',
          away: awayStats.possessions,
          home: homeStats.possessions,
          awayCompareValue: awayStats.possessions,
          homeCompareValue: homeStats.possessions,
          awayRank: awayStats.possessions_rank,
          homeRank: homeStats.possessions_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'FG',
          title: 'FG',
          tooltip: 'Field goals per game',
          away: awayStats.field_goal,
          home: homeStats.field_goal,
          awayCompareValue: awayStats.field_goal,
          homeCompareValue: homeStats.field_goal,
          awayRank: awayStats.field_goal_rank,
          homeRank: homeStats.field_goal_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'FGA',
          title: 'FGA',
          tooltip: 'Field goal attempts per game',
          away: awayStats.field_goal_attempts,
          home: homeStats.field_goal_attempts,
          awayCompareValue: awayStats.field_goal_attempts,
          homeCompareValue: homeStats.field_goal_attempts,
          awayRank: awayStats.field_goal_attempts_rank,
          homeRank: homeStats.field_goal_attempts_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'FG%',
          title: 'FG%',
          tooltip: 'Field goal percentage',
          away: `${awayStats.field_goal_percentage || 0}%`,
          home: `${homeStats.field_goal_percentage || 0}%`,
          awayCompareValue: awayStats.field_goal_percentage,
          homeCompareValue: homeStats.field_goal_percentage,
          awayRank: awayStats.field_goal_percentage_rank,
          homeRank: homeStats.field_goal_percentage_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: '2P',
          title: '2P',
          tooltip: '2 point field goals per game',
          away: awayStats.two_point_field_goal,
          home: homeStats.two_point_field_goal,
          awayCompareValue: awayStats.two_point_field_goal,
          homeCompareValue: homeStats.two_point_field_goal,
          awayRank: awayStats.two_point_field_goal_rank,
          homeRank: homeStats.two_point_field_goal_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: '2PA',
          title: '2PA',
          tooltip: '2 point field goal attempts per game',
          away: awayStats.two_point_field_goal_attempts,
          home: homeStats.two_point_field_goal_attempts,
          awayCompareValue: awayStats.two_point_field_goal_attempts,
          homeCompareValue: homeStats.two_point_field_goal_attempts,
          awayRank: awayStats.two_point_field_goal_attempts_rank,
          homeRank: homeStats.two_point_field_goal_attempts_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: '2P%',
          title: '2P%',
          tooltip: '2 point field goal percentage',
          away: `${awayStats.two_point_field_goal_percentage || 0}%`,
          home: `${homeStats.two_point_field_goal_percentage || 0}%`,
          awayCompareValue: awayStats.two_point_field_goal_percentage,
          homeCompareValue: homeStats.two_point_field_goal_percentage,
          awayRank: awayStats.two_point_field_goal_percentage_rank,
          homeRank: homeStats.two_point_field_goal_percentage_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: '3P',
          title: '3P',
          tooltip: '3 point field goals per game',
          away: awayStats.three_point_field_goal,
          home: homeStats.three_point_field_goal,
          awayCompareValue: awayStats.three_point_field_goal,
          homeCompareValue: homeStats.three_point_field_goal,
          awayRank: awayStats.three_point_field_goal_rank,
          homeRank: homeStats.three_point_field_goal_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: '3PA',
          title: '3PA',
          tooltip: '3 point field goal attempts per game',
          away: awayStats.three_point_field_goal_attempts,
          home: homeStats.three_point_field_goal_attempts,
          awayCompareValue: awayStats.three_point_field_goal_attempts,
          homeCompareValue: homeStats.three_point_field_goal_attempts,
          awayRank: awayStats.three_point_field_goal_attempts_rank,
          homeRank: homeStats.three_point_field_goal_attempts_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: '3P%',
          title: '3P%',
          tooltip: '3 point field goal percentage',
          away: `${awayStats.three_point_field_goal_percentage || 0}%`,
          home: `${homeStats.three_point_field_goal_percentage || 0}%`,
          awayCompareValue: awayStats.three_point_field_goal_percentage,
          homeCompareValue: homeStats.three_point_field_goal_percentage,
          awayRank: awayStats.three_point_field_goal_percentage_rank,
          homeRank: homeStats.three_point_field_goal_percentage_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'FT',
          title: 'FT',
          tooltip: 'Free throws per game',
          away: awayStats.free_throws,
          home: homeStats.free_throws,
          awayCompareValue: awayStats.free_throws,
          homeCompareValue: homeStats.free_throws,
          awayRank: awayStats.free_throws_rank,
          homeRank: homeStats.free_throws_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'FTA',
          title: 'FTA',
          tooltip: 'Free throw attempts per game',
          away: awayStats.free_throw_attempts,
          home: homeStats.free_throw_attempts,
          awayCompareValue: awayStats.free_throw_attempts,
          homeCompareValue: homeStats.free_throw_attempts,
          awayRank: awayStats.free_throw_attempts_rank,
          homeRank: homeStats.free_throw_attempts_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'FT%',
          title: 'FT%',
          tooltip: 'Free throw percentage',
          away: `${awayStats.free_throw_percentage || 0}%`,
          home: `${homeStats.free_throw_percentage || 0}%`,
          awayCompareValue: awayStats.free_throw_percentage,
          homeCompareValue: homeStats.free_throw_percentage,
          awayRank: awayStats.free_throw_percentage_rank,
          homeRank: homeStats.free_throw_percentage_rank,
          favored: 'higher',
          showDifference: true,
        },
      ],
    },
    {
      name: 'Special',
      rows: [
        {
          name: 'ORB',
          title: 'ORB',
          tooltip: 'Offensive rebounds',
          away: awayStats.offensive_rebounds,
          home: homeStats.offensive_rebounds,
          awayCompareValue: awayStats.offensive_rebounds,
          homeCompareValue: homeStats.offensive_rebounds,
          awayRank: awayStats.offensive_rebounds_rank,
          homeRank: homeStats.offensive_rebounds_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'DRB',
          title: 'DRB',
          tooltip: 'Defensive rebounds',
          away: awayStats.defensive_rebounds,
          home: homeStats.defensive_rebounds,
          awayCompareValue: awayStats.defensive_rebounds,
          homeCompareValue: homeStats.defensive_rebounds,
          awayRank: awayStats.defensive_rebounds_rank,
          homeRank: homeStats.defensive_rebounds_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'AST',
          title: 'AST',
          tooltip: 'Assists',
          away: awayStats.assists,
          home: homeStats.assists,
          awayCompareValue: awayStats.assists,
          homeCompareValue: homeStats.assists,
          awayRank: awayStats.assists_rank,
          homeRank: homeStats.assists_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'STL',
          title: 'STL',
          tooltip: 'Steals',
          away: awayStats.steals,
          home: homeStats.steals,
          awayCompareValue: awayStats.steals,
          homeCompareValue: homeStats.steals,
          awayRank: awayStats.steals_rank,
          homeRank: homeStats.steals_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'BLK',
          title: 'BLK',
          tooltip: 'Blocks',
          away: awayStats.blocks,
          home: homeStats.blocks,
          awayCompareValue: awayStats.blocks,
          homeCompareValue: homeStats.blocks,
          awayRank: awayStats.blocks_rank,
          homeRank: homeStats.blocks_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'TOV',
          title: 'TOV',
          tooltip: 'Turnovers',
          away: awayStats.turnovers,
          home: homeStats.turnovers,
          awayCompareValue: awayStats.turnovers,
          homeCompareValue: homeStats.turnovers,
          awayRank: awayStats.turnovers_rank,
          homeRank: homeStats.turnovers_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'PF',
          title: 'PF',
          tooltip: 'Fouls',
          away: awayStats.fouls,
          home: homeStats.fouls,
          awayCompareValue: awayStats.fouls,
          homeCompareValue: homeStats.fouls,
          awayRank: awayStats.fouls_rank,
          homeRank: homeStats.fouls_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'FE',
          title: 'Fatigue rating',
          away: awayStats.fatigue,
          home: homeStats.fatigue,
          awayCompareValue: awayStats.fatigue,
          homeCompareValue: homeStats.fatigue,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'DES',
          title: 'Desperation rating',
          away: awayStats.desperation,
          home: homeStats.desperation,
          awayCompareValue: awayStats.desperation,
          homeCompareValue: homeStats.desperation,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'OVC',
          title: 'Over confidence rating',
          away: awayStats.over_confidence,
          home: homeStats.over_confidence,
          awayCompareValue: awayStats.over_confidence,
          homeCompareValue: homeStats.over_confidence,
          favored: 'lower',
          showDifference: true,
        },
      ],
    },
    {
      name: 'Defensive',
      rows: [
        {
          name: 'FG',
          title: 'FG',
          tooltip: 'Oppenent field goals per game',
          away: awayStats.opponent_field_goal,
          home: homeStats.opponent_field_goal,
          awayCompareValue: awayStats.opponent_field_goal,
          homeCompareValue: homeStats.opponent_field_goal,
          awayRank: awayStats.opponent_field_goal_rank,
          homeRank: homeStats.opponent_field_goal_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'FGA',
          title: 'FGA',
          tooltip: 'Oppenent field goal attempts per game',
          away: awayStats.opponent_field_goal_attempts,
          home: homeStats.opponent_field_goal_attempts,
          awayCompareValue: awayStats.opponent_field_goal_attempts,
          homeCompareValue: homeStats.opponent_field_goal_attempts,
          awayRank: awayStats.opponent_field_goal_attempts_rank,
          homeRank: homeStats.opponent_field_goal_attempts_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'FG%',
          title: 'FG%',
          tooltip: 'Oppenent field goal percentage',
          away: `${awayStats.opponent_field_goal_percentage || 0}%`,
          home: `${homeStats.opponent_field_goal_percentage || 0}%`,
          awayCompareValue: awayStats.opponent_field_goal_percentage,
          homeCompareValue: homeStats.opponent_field_goal_percentage,
          awayRank: awayStats.opponent_field_goal_percentage_rank,
          homeRank: homeStats.opponent_field_goal_percentage_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'ORB',
          title: 'ORB',
          tooltip: 'Oppenent Offensive rebounds per game',
          away: awayStats.opponent_offensive_rebounds,
          home: homeStats.opponent_offensive_rebounds,
          awayCompareValue: awayStats.opponent_offensive_rebounds,
          homeCompareValue: homeStats.opponent_offensive_rebounds,
          awayRank: awayStats.opponent_offensive_rebounds_rank,
          homeRank: homeStats.opponent_offensive_rebounds_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'DRB',
          title: 'DRB',
          tooltip: 'Oppenent Defensive rebounds per game',
          away: awayStats.opponent_defensive_rebounds,
          home: homeStats.opponent_defensive_rebounds,
          awayCompareValue: awayStats.opponent_defensive_rebounds,
          homeCompareValue: homeStats.opponent_defensive_rebounds,
          awayRank: awayStats.opponent_defensive_rebounds_rank,
          homeRank: homeStats.opponent_defensive_rebounds_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'AST',
          title: 'AST',
          tooltip: 'Oppenent Assists per game',
          away: awayStats.opponent_assists,
          home: homeStats.opponent_assists,
          awayCompareValue: awayStats.opponent_assists,
          homeCompareValue: homeStats.opponent_assists,
          awayRank: awayStats.opponent_assists_rank,
          homeRank: homeStats.opponent_assists_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'STL',
          title: 'STL',
          tooltip: 'Oppenent Steals per game',
          away: awayStats.opponent_steals,
          home: homeStats.opponent_steals,
          awayCompareValue: awayStats.opponent_steals,
          homeCompareValue: homeStats.opponent_steals,
          awayRank: awayStats.opponent_steals_rank,
          homeRank: homeStats.opponent_steals_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'BLK',
          title: 'BLK',
          tooltip: 'Oppenent Blocks per game',
          away: awayStats.opponent_blocks,
          home: homeStats.opponent_blocks,
          awayCompareValue: awayStats.opponent_blocks,
          homeCompareValue: homeStats.opponent_blocks,
          awayRank: awayStats.opponent_blocks_rank,
          homeRank: homeStats.opponent_blocks_rank,
          favored: 'lower',
          showDifference: true,
        },
        {
          name: 'TOV',
          title: 'TOV',
          tooltip: 'Oppenent Turnovers per game',
          away: awayStats.opponent_turnovers,
          home: homeStats.opponent_turnovers,
          awayCompareValue: awayStats.opponent_turnovers,
          homeCompareValue: homeStats.opponent_turnovers,
          awayRank: awayStats.opponent_turnovers_rank,
          homeRank: homeStats.opponent_turnovers_rank,
          favored: 'higher',
          showDifference: true,
        },
        {
          name: 'PF',
          title: 'PF',
          tooltip: 'Oppenent Turnovers per game',
          away: awayStats.opponent_fouls,
          home: homeStats.opponent_fouls,
          awayCompareValue: awayStats.opponent_fouls,
          homeCompareValue: homeStats.opponent_fouls,
          awayRank: awayStats.opponent_fouls_rank,
          homeRank: homeStats.opponent_fouls_rank,
          favored: 'higher',
          showDifference: true,
        },
      ],
    },
  ];
};

const Client = ({ game }) => {
  const gameStats = useAppSelector((state) => state.gameReducer.gameStats);

  let numberOfTeams = CBB.getNumberOfD1Teams(game.season);

  if (game.organization_id === Organization.getCFBID()) {
    numberOfTeams = CFB.getNumberOfTeams({ division_id: game.division_id, season: game.season });
  }

  const homeStats = (gameStats[game.game_id] && gameStats[game.game_id].historical[game.home_team_id]) || {};
  const awayStats = (gameStats[game.game_id] && gameStats[game.game_id].historical[game.away_team_id]) || {};


  const sections = getSections({ homeStats, awayStats });


  return (
    <div style = {{ padding: '0px 5px 20px 5px' }}>
      <PredictionLine game={game} />

      {sections.map((section) => {
        return (
          <React.Fragment key = {section.name}>
            <Typography style = {{ textAlign: 'center', margin: '10px 0px' }} variant = 'body1'>{section.name}</Typography>
            <CompareStatistic max = {numberOfTeams} season = {game.season} paper = {true} rows = {section.rows} />
          </React.Fragment>
        );
      })}
    </div>
  );
};

export default Client;
