/* eslint-disable no-nested-ternary */

import Organization from './Organization';

type TableColumn = {
  id: string;
  numeric: boolean;
  label: string;
  tooltip: string;
  sticky?: boolean;
  disabled?: boolean;
  sort?: 'lower' | 'higher';
  organization_ids: string[];
  views: string[];
  graphable: boolean;
  widths?: {
    [breakpoint: string]: number;
    default: number;
  }
}

export type TableColumnsType = {
  [key: string]: TableColumn;
};

class TableColumns {
  public static getColumns(
    { organization_id, view, graphable, disabled }:
    { organization_id: string; view: string; graphable?: boolean; disabled?: boolean; },
  ): TableColumnsType {
    const allViews = [
      'team',
      'conference',
      'coach',
      'player',
      'transfer',
    ];

    const columns: TableColumnsType = {
      rank: {
        id: 'rank',
        numeric: true,
        label: 'Rk',
        tooltip: 'srating.io Rank',
        sticky: true,
        disabled: true,
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: allViews,
        graphable: true,
        widths: {
          default: 50,
          425: 40,
        },
      },
      name: {
        id: 'name',
        numeric: false,
        label: (view === 'player' || view === 'transfer' ? 'Player' : (view === 'conference' ? 'Conference' : (view === 'coach' ? 'Coach' : 'Team'))),
        tooltip: (view === 'player' || view === 'transfer' ? 'Player name' : (view === 'conference' ? 'Conference name' : (view === 'coach' ? 'Coach name' : 'Team name'))),
        sticky: true,
        disabled: true,
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: allViews,
        graphable: false,
        widths: {
          default: 125,
          425: 85,
        },
      },
      team_name: {
        id: 'team_name',
        numeric: false,
        label: (view === 'transfer' ? 'Prev. team' : 'Team'),
        tooltip: (view === 'transfer' ? 'Previous team name' : 'Team name'),
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['player', 'transfer', 'coach'],
        graphable: false,
        widths: {
          default: 85,
        },
      },
      conference_code: {
        id: 'conference_code',
        numeric: false,
        label: 'Conf.',
        tooltip: 'Conference',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'player', 'transfer'],
        graphable: false,
        widths: {
          default: 100,
        },
      },
      rank_delta_combo: {
        id: 'rank_delta_combo',
        numeric: true,
        label: 'Δ 1/7',
        tooltip: 'Rank difference since last ranking (1 day / 7 days)',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: allViews,
        graphable: false,
      },
      rank_delta_one: {
        id: 'rank_delta_one',
        numeric: true,
        label: 'Δ',
        tooltip: 'Rank difference since last ranking (1 day)',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: allViews,
        graphable: true,
      },
      rank_delta_seven: {
        id: 'rank_delta_seven',
        numeric: true,
        label: 'Δ7',
        tooltip: 'Rank difference since last week ranking (7 days)',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: allViews,
        graphable: true,
      },
      elo: {
        id: 'elo',
        numeric: true,
        label: 'SR',
        tooltip: 'srating.io elo rating',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: allViews,
        graphable: true,
      },
      field_goal: {
        id: 'field_goal',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'FG-T' : 'FG'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total field goals made in season' : 'Average field goals per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      field_goal_attempts: {
        id: 'field_goal_attempts',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'FGA-T' : 'FGA'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total field goal attempts in season' : 'Average field goal attempts per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      field_goal_percentage: {
        id: 'field_goal_percentage',
        numeric: true,
        label: 'FG%',
        tooltip: 'Field goal percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      two_point_field_goal: {
        id: 'two_point_field_goal',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? '2FG-T' : '2FG'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total two point field goals made in season' : 'Average two point field goals per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      two_point_field_goal_attempts: {
        id: 'two_point_field_goal_attempts',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? '2FGA-T' : '2FGA'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total two point field goal attempts in season' : 'Average two point field goal attempts per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      two_point_field_goal_percentage: {
        id: 'two_point_field_goal_percentage',
        numeric: true,
        label: '2FG%',
        tooltip: 'Two point field goal percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      three_point_field_goal: {
        id: 'three_point_field_goal',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? '3FG-T' : '3FG'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total three point field goals made in season' : 'Average three point field goals per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      three_point_field_goal_attempts: {
        id: 'three_point_field_goal_attempts',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? '3FGA-T' : '3FGA'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total three field goal attempts in season' : 'Average three field goal attempts per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      three_point_field_goal_percentage: {
        id: 'three_point_field_goal_percentage',
        numeric: true,
        label: '3FG%',
        tooltip: 'Three field goal percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      free_throws: {
        id: 'free_throws',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'FT-T' : 'FT'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total free throws made in season' : 'Average free throws per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      free_throw_attempts: {
        id: 'free_throw_attempts',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'FTA-T' : 'FTA'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total free throw attempts in season' : 'Average free throw attempts per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      free_throw_percentage: {
        id: 'free_throw_percentage',
        numeric: true,
        label: 'FT%',
        tooltip: 'Free throw percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      offensive_rebounds: {
        id: 'offensive_rebounds',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'ORB-T' : 'ORB'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total offensive rebounds in season' : 'Average offensive rebounds per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      defensive_rebounds: {
        id: 'defensive_rebounds',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'DRB-T' : 'DRB'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total defensive rebounds in season' : 'Average defensive rebounds per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      total_rebounds: {
        id: 'total_rebounds',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'TRB-T' : 'TRB'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total rebounds in season' : 'Average total rebounds per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      assists: {
        id: 'assists',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'AST-T' : 'AST'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total assists in season' : 'Average assists per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      steals: {
        id: 'steals',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'STL-T' : 'STL'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total steals in season' : 'Average steals per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      blocks: {
        id: 'blocks',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'BLK-T' : 'BLK'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total blocks in season' : 'Average blocks per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      turnovers: {
        id: 'turnovers',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'TOV-T' : 'TOV'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total turnovers in season' : 'Average turnovers per game'),
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      fouls: {
        id: 'fouls',
        numeric: true,
        label: (view === 'player' || view === 'transfer' ? 'PF-T' : 'PF'),
        tooltip: (view === 'player' || view === 'transfer' ? 'Total fouls in season' : 'Average fouls per game'),
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      points: {
        id: 'points',
        numeric: true,
        label: 'PTS',
        tooltip: (view === 'player' || view === 'transfer' ? 'Total points in season' : 'Average points per game'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      offensive_rating: {
        id: 'offensive_rating',
        numeric: true,
        label: 'ORT',
        tooltip: 'Offensive rating ((PTS / Poss) * 100)',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      defensive_rating: {
        id: 'defensive_rating',
        numeric: true,
        label: 'DRT',
        tooltip: 'Defensive rating ((Opp. PTS / Opp. Poss) * 100)',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      efficiency_rating: {
        id: 'efficiency_rating',
        numeric: true,
        label: (view === 'team' ? 'EM' : 'ERT'),
        tooltip: (view === 'team' ? 'Efficiency margin (Offensive rating - Defensive rating)' : 'Efficiency rating'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      record: {
        id: 'record',
        numeric: false,
        label: 'W/L',
        tooltip: 'Win/Loss',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: false,
      },
      conf_record: {
        id: 'conf_record',
        numeric: false,
        label: 'CR',
        tooltip: 'Conference Record Win/Loss',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team'],
        graphable: false,
      },
      games: {
        id: 'games',
        numeric: true,
        label: 'G',
        tooltip: 'Games played',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: allViews,
        graphable: true,
      },
      wins: {
        id: 'wins',
        numeric: true,
        label: 'Wins',
        tooltip: 'Wins',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference', 'coach'],
        graphable: true,
      },
      losses: {
        id: 'losses',
        numeric: true,
        label: 'Losses',
        tooltip: 'Losses',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference', 'coach'],
        graphable: true,
      },
      neutralwins: {
        id: 'neutralwins',
        numeric: true,
        label: 'Neut. wins',
        tooltip: 'Neutral wins',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference', 'coach'],
        graphable: true,
      },
      neutrallosses: {
        id: 'neutrallosses',
        numeric: true,
        label: 'Neut. losses',
        tooltip: 'Neutral losses',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference', 'coach'],
        graphable: true,
      },
      homewins: {
        id: 'homewins',
        numeric: true,
        label: 'Home wins',
        tooltip: 'Home wins',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference', 'coach'],
        graphable: true,
      },
      homelosses: {
        id: 'homelosses',
        numeric: true,
        label: 'Home losses',
        tooltip: 'Home losses',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference', 'coach'],
        graphable: true,
      },
      roadwins: {
        id: 'roadwins',
        numeric: true,
        label: 'Road wins',
        tooltip: 'Road wins',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference', 'coach'],
        graphable: true,
      },
      roadlosses: {
        id: 'roadlosses',
        numeric: true,
        label: 'Road losses',
        tooltip: 'Road losses',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference', 'coach'],
        graphable: true,
      },
      confwins: {
        id: 'confwins',
        numeric: false,
        label: 'CONF W',
        tooltip: 'Conference Total Wins',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'coach'],
        graphable: true,
      },
      conflosses: {
        id: 'conflosses',
        numeric: false,
        label: 'CONF L',
        tooltip: 'Conference Total Losses',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'coach'],
        graphable: true,
      },
      nonconfwins: {
        id: 'nonconfwins',
        numeric: false,
        label: 'NONC W',
        tooltip: 'Non-Conference Total Wins',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'coach', 'conference'],
        graphable: true,
      },
      nonconflosses: {
        id: 'nonconflosses',
        numeric: false,
        label: 'NONC L',
        tooltip: 'Non-Conference Total Losses',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'coach', 'conference'],
        graphable: true,
      },
      win_percentage: {
        id: 'win_percentage',
        numeric: true,
        label: 'W%',
        tooltip: 'Win percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['coach'],
        graphable: true,
      },
      conf_win_percentage: {
        id: 'conf_win_percentage',
        numeric: true,
        label: 'C%',
        tooltip: 'Conference win percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['coach'],
        graphable: true,
      },
      nonconf_win_percentage: {
        id: 'nonconf_win_percentage',
        numeric: true,
        label: 'NON C%',
        tooltip: 'Non-Conference win percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['coach'],
        graphable: true,
      },
      home_win_percentage: {
        id: 'home_win_percentage',
        numeric: true,
        label: 'H%',
        tooltip: 'Home win percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['coach'],
        graphable: true,
      },
      road_win_percentage: {
        id: 'road_win_percentage',
        numeric: true,
        label: 'R%',
        tooltip: 'Road win percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['coach'],
        graphable: true,
      },
      neutral_win_percentage: {
        id: 'neutral_win_percentage',
        numeric: true,
        label: 'N%',
        tooltip: 'Neutral win percentage',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['coach'],
        graphable: true,
      },
      streak: {
        id: 'streak',
        numeric: true,
        label: 'Streak',
        tooltip: 'Number of wins or losses in a row (negative for loss)',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team'],
        graphable: true,
      },
      win_margin: {
        id: 'win_margin',
        numeric: true,
        label: 'Win margin',
        tooltip: 'Win margin',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      loss_margin: {
        id: 'loss_margin',
        numeric: true,
        label: 'Loss margin',
        tooltip: 'Loss margin',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      confwin_margin: {
        id: 'confwin_margin',
        numeric: true,
        label: 'C Win margin',
        tooltip: 'Conference Win margin',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team'],
        graphable: true,
      },
      confloss_margin: {
        id: 'confloss_margin',
        numeric: true,
        label: 'C Loss margin',
        tooltip: 'Conference Loss margin',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team'],
        graphable: true,
      },
      nonconfwin_margin: {
        id: 'nonconfwin_margin',
        numeric: false,
        label: 'NONC W Margin',
        tooltip: 'Non-Conference Avg. # of Win Margin',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['conference'],
        graphable: true,
      },
      nonconfloss_margin: {
        id: 'nonconfloss_margin',
        numeric: false,
        label: 'NONC L Margin',
        tooltip: 'Non-Conference Avg. # of Loss Margin',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['conference'],
        graphable: true,
      },
      possessions: {
        id: 'possessions',
        numeric: true,
        label: 'Poss.',
        tooltip: 'Average possessions per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      pace: {
        id: 'pace',
        numeric: true,
        label: 'Pace',
        tooltip: 'Average pace per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      minutes_played: {
        id: 'minutes_played',
        numeric: true,
        label: 'MP',
        tooltip: (view === 'team' ? 'Average minutes played per game' : 'Total minutes played'),
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'player', 'transfer'],
        graphable: true,
      },
      adjusted_efficiency_rating: {
        id: 'adjusted_efficiency_rating',
        numeric: true,
        label: 'aEM',
        tooltip: 'Adjusted Efficiency margin (Offensive rating - Defensive rating) + aSOS',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_offensive_rating: {
        id: 'opponent_offensive_rating',
        numeric: true,
        label: 'oORT',
        tooltip: 'Opponent average Offensive rating',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_defensive_rating: {
        id: 'opponent_defensive_rating',
        numeric: true,
        label: 'oDRT',
        tooltip: 'Opponent average Defensive rating ',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_efficiency_rating: {
        id: 'opponent_efficiency_rating',
        numeric: true,
        label: 'aSOS',
        tooltip: 'Strength of schedule (Opponent Efficiency margin (oORT - oDRT))',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      elo_sos: {
        id: 'elo_sos',
        numeric: true,
        label: 'eSOS',
        tooltip: 'Strength of schedule (opponent elo)',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference', 'coach'],
        graphable: true,
      },
      opponent_field_goal: {
        id: 'opponent_field_goal',
        numeric: true,
        label: 'Opp. FG',
        tooltip: 'Opponent average field goals per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_field_goal_attempts: {
        id: 'opponent_field_goal_attempts',
        numeric: true,
        label: 'Opp. FGA',
        tooltip: 'Opponent average field goal attempts per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_field_goal_percentage: {
        id: 'opponent_field_goal_percentage',
        numeric: true,
        label: 'Opp. FG%',
        tooltip: 'Opponent average field goal percentage per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_two_point_field_goal: {
        id: 'opponent_two_point_field_goal',
        numeric: true,
        label: 'Opp. 2FG',
        tooltip: 'Opponent average two point field goals per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_two_point_field_goal_attempts: {
        id: 'opponent_two_point_field_goal_attempts',
        numeric: true,
        label: 'Opp. 2FGA',
        tooltip: 'Opponent average two point field goal attempts per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_two_point_field_goal_percentage: {
        id: 'opponent_two_point_field_goal_percentage',
        numeric: true,
        label: 'Opp. 2FG%',
        tooltip: 'Opponent average two point field goal percentage per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_three_point_field_goal: {
        id: 'opponent_three_point_field_goal',
        numeric: true,
        label: 'Opp. 3FG',
        tooltip: 'Opponent average three point field goals per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_three_point_field_goal_attempts: {
        id: 'opponent_three_point_field_goal_attempts',
        numeric: true,
        label: 'Opp. 3FGA',
        tooltip: 'Opponent average three point field goal attempts per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_three_point_field_goal_percentage: {
        id: 'opponent_three_point_field_goal_percentage',
        numeric: true,
        label: 'Opp. 3FG%',
        tooltip: 'Opponent average three point field goal percentage per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_free_throws: {
        id: 'opponent_free_throws',
        numeric: true,
        label: 'Opp. FT',
        tooltip: 'Opponent average free throws per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_free_throw_attempts: {
        id: 'opponent_free_throw_attempts',
        numeric: true,
        label: 'Opp. FTA',
        tooltip: 'Opponent average free throw attempts per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_free_throw_percentage: {
        id: 'opponent_free_throw_percentage',
        numeric: true,
        label: 'Opp. FT%',
        tooltip: 'Opponent average free throw percentage per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_offensive_rebounds: {
        id: 'opponent_offensive_rebounds',
        numeric: true,
        label: 'Opp. ORB',
        tooltip: 'Opponent average offensive rebounds per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_defensive_rebounds: {
        id: 'opponent_defensive_rebounds',
        numeric: true,
        label: 'Opp. DRB',
        tooltip: 'Opponent average defensive rebounds per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_total_rebounds: {
        id: 'opponent_total_rebounds',
        numeric: true,
        label: 'Opp. TRB',
        tooltip: 'Opponent average total rebounds per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_assists: {
        id: 'opponent_assists',
        numeric: true,
        label: 'Opp. AST',
        tooltip: 'Opponent average assists per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_steals: {
        id: 'opponent_steals',
        numeric: true,
        label: 'Opp. STL',
        tooltip: 'Opponent average steals per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_blocks: {
        id: 'opponent_blocks',
        numeric: true,
        label: 'Opp. BLK',
        tooltip: 'Opponent average blocks per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_turnovers: {
        id: 'opponent_turnovers',
        numeric: true,
        label: 'Opp. TOV',
        tooltip: 'Opponent average turnovers per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_fouls: {
        id: 'opponent_fouls',
        numeric: true,
        label: 'Opp. PF',
        tooltip: 'Opponent average fouls per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_points: {
        id: 'opponent_points',
        numeric: true,
        label: 'Opp. PTS',
        tooltip: 'Opponent average points per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_possessions: {
        id: 'opponent_possessions',
        numeric: true,
        label: 'Opp. Poss.',
        tooltip: 'Opponent average possessions per game',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_minutes_played: {
        id: 'opponent_minutes_played',
        numeric: true,
        label: 'Opp. MP',
        tooltip: 'Opponent average minutes played per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['team'],
        graphable: true,
      },
      ap_rank: {
        id: 'ap_rank',
        numeric: true,
        label: 'AP',
        tooltip: 'Associated Press rank',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team'],
        graphable: false,
      },
      kenpom_rank: {
        id: 'kenpom_rank',
        numeric: true,
        label: 'KP',
        tooltip: 'kenpom.com rank',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team'],
        graphable: false,
      },
      srs_rank: {
        id: 'srs_rank',
        numeric: true,
        label: 'SRS',
        tooltip: 'Simple rating system rank',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team'],
        graphable: false,
      },
      net_rank: {
        id: 'net_rank',
        numeric: true,
        label: 'NET',
        tooltip: 'NET rank',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team'],
        graphable: false,
      },
      coaches_rank: {
        id: 'coaches_rank',
        numeric: true,
        label: 'Coaches',
        tooltip: 'Coaches poll rank',
        sort: 'lower',
        organization_ids: [Organization.getCBBID()],
        views: ['team'],
        graphable: false,
      },
      committed: {
        id: 'committed',
        numeric: false,
        label: 'Committed',
        tooltip: 'Player committed',
        organization_ids: [Organization.getCBBID()],
        views: ['transfer'],
        graphable: false,
      },
      committed_team_name: {
        id: 'committed_team_name',
        numeric: false,
        label: 'New team',
        tooltip: 'New (committed) team name',
        organization_ids: [Organization.getCBBID()],
        views: ['transfer'],
        graphable: false,
      },
      position: {
        id: 'position',
        numeric: false,
        label: 'Position',
        tooltip: 'Player position',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['player', 'transfer'],
        graphable: false,
      },
      number: {
        id: 'number',
        numeric: false,
        label: 'Number',
        tooltip: 'Jersey number',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['player', 'transfer'],
        graphable: false,
      },
      height: {
        id: 'height',
        numeric: true,
        label: 'Ht.',
        tooltip: 'Player height',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['player', 'transfer'],
        graphable: false,
      },
      minutes_per_game: {
        id: 'minutes_per_game',
        numeric: true,
        label: 'MPG',
        tooltip: 'Minutes played per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID(), Organization.getCFBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      points_per_game: {
        id: 'points_per_game',
        numeric: true,
        label: 'PPG',
        tooltip: 'Points per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      field_goal_per_game: {
        id: 'field_goal_per_game',
        numeric: true,
        label: 'FG',
        tooltip: 'Average field goals per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      field_goal_attempts_per_game: {
        id: 'field_goal_attempts_per_game',
        numeric: true,
        label: 'FGA',
        tooltip: 'Average field goal attempts per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      two_point_field_goal_per_game: {
        id: 'two_point_field_goal_per_game',
        numeric: true,
        label: '2FG',
        tooltip: 'Average two point field goals per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      two_point_field_goal_attempts_per_game: {
        id: 'two_point_field_goal_attempts_per_game',
        numeric: true,
        label: '2FGA',
        tooltip: 'Average two point field goal attempts per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      three_point_field_goal_per_game: {
        id: 'three_point_field_goal_per_game',
        numeric: true,
        label: '3FG',
        tooltip: 'Average three point field goals per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      three_point_field_goal_attempts_per_game: {
        id: 'three_point_field_goal_attempts_per_game',
        numeric: true,
        label: '3FGA',
        tooltip: 'Average three field goal attempts per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      free_throws_per_game: {
        id: 'free_throws_per_game',
        numeric: true,
        label: 'FT',
        tooltip: 'Average free throws per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      free_throw_attempts_per_game: {
        id: 'free_throw_attempts_per_game',
        numeric: true,
        label: 'FTA',
        tooltip: 'Average free throw attempts per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      offensive_rebounds_per_game: {
        id: 'offensive_rebounds_per_game',
        numeric: true,
        label: 'ORB',
        tooltip: 'Offensive rebounds per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      defensive_rebounds_per_game: {
        id: 'defensive_rebounds_per_game',
        numeric: true,
        label: 'DRB',
        tooltip: 'Defensive rebounds per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      total_rebounds_per_game: {
        id: 'total_rebounds_per_game',
        numeric: true,
        label: 'TRB',
        tooltip: 'Total rebounds per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      assists_per_game: {
        id: 'assists_per_game',
        numeric: true,
        label: 'AST',
        tooltip: 'Assists per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      steals_per_game: {
        id: 'steals_per_game',
        numeric: true,
        label: 'STL',
        tooltip: 'Steals per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      blocks_per_game: {
        id: 'blocks_per_game',
        numeric: true,
        label: 'BLK',
        tooltip: 'Blocks per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      turnovers_per_game: {
        id: 'turnovers_per_game',
        numeric: true,
        label: 'TO',
        tooltip: 'Blocks per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      fouls_per_game: {
        id: 'fouls_per_game',
        numeric: true,
        label: 'PF',
        tooltip: 'Fouls per game',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      player_efficiency_rating: {
        id: 'player_efficiency_rating',
        numeric: true,
        label: 'PER',
        tooltip: 'Player efficiency rating metric',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      true_shooting_percentage: {
        id: 'true_shooting_percentage',
        numeric: true,
        label: 'TS%',
        tooltip: 'True shooting percentage, takes into account all field goals and free throws.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      effective_field_goal_percentage: {
        id: 'effective_field_goal_percentage',
        numeric: true,
        label: 'eFG%',
        tooltip: 'Effective field goal percentage, adjusted field goal % since 3 points greater than 2.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      offensive_rebound_percentage: {
        id: 'offensive_rebound_percentage',
        numeric: true,
        label: 'ORB%',
        tooltip: 'Offensive rebound percentage, estimate of % of offensive rebounds player had while on floor.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      defensive_rebound_percentage: {
        id: 'defensive_rebound_percentage',
        numeric: true,
        label: 'DRB%',
        tooltip: 'Defensive rebound percentage, estimate of % of defensive rebounds player had while on floor.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      total_rebound_percentage: {
        id: 'total_rebound_percentage',
        numeric: true,
        label: 'TRB%',
        tooltip: 'Total rebound percentage, estimate of % of total rebounds player had while on floor.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      assist_percentage: {
        id: 'assist_percentage',
        numeric: true,
        label: 'AST%',
        tooltip: 'Assist percentage, estimate of % of assists player had while on floor.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      steal_percentage: {
        id: 'steal_percentage',
        numeric: true,
        label: 'STL%',
        tooltip: 'Steal percentage, estimate of % of steals player had while on floor.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      block_percentage: {
        id: 'block_percentage',
        numeric: true,
        label: 'BLK%',
        tooltip: 'Block percentage, estimate of % of blocks player had while on floor.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      turnover_percentage: {
        id: 'turnover_percentage',
        numeric: true,
        label: 'TOV%',
        tooltip: 'Turnover percentage, estimate of % of turnovers player had while on floor.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      usage_percentage: {
        id: 'usage_percentage',
        numeric: true,
        label: 'USG%',
        tooltip: 'Usage percentage, estimate of % of plays ran through player while on floor.',
        sort: 'higher',
        organization_ids: [Organization.getCBBID()],
        views: ['player', 'transfer'],
        graphable: true,
      },
      passing_attempts: {
        id: 'passing_attempts',
        numeric: true,
        label: 'Pass att.',
        tooltip: 'Passing attempts',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_completions: {
        id: 'passing_completions',
        numeric: true,
        label: 'Pass comp.',
        tooltip: 'Passing completions',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_yards: {
        id: 'passing_yards',
        numeric: true,
        label: 'Pass yards',
        tooltip: 'Passing yards',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_completion_percentage: {
        id: 'passing_completion_percentage',
        numeric: true,
        label: 'Pass comp. %',
        tooltip: 'Passing completions percentage',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_yards_per_attempt: {
        id: 'passing_yards_per_attempt',
        numeric: true,
        label: 'Pass yards per att.',
        tooltip: 'Passing yard per attempt',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_yards_per_completion: {
        id: 'passing_yards_per_completion',
        numeric: true,
        label: 'Pass yards per comp.',
        tooltip: 'Passing yards per completion',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_touchdowns: {
        id: 'passing_touchdowns',
        numeric: true,
        label: 'Pass TD',
        tooltip: 'Passing touchdowns',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_interceptions: {
        id: 'passing_interceptions',
        numeric: true,
        label: 'Pass int.',
        tooltip: 'Passing interceptions',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_rating_pro: {
        id: 'passing_rating_pro',
        numeric: true,
        label: 'QBR(p)',
        tooltip: 'Quarter back rating (pro)',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_rating_college: {
        id: 'passing_rating_college',
        numeric: true,
        label: 'QBR(c)',
        tooltip: 'Quarter back rating (college)',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      passing_long: {
        id: 'passing_long',
        numeric: true,
        label: 'Pass long',
        tooltip: 'Passing long',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      rushing_attempts: {
        id: 'rushing_attempts',
        numeric: true,
        label: 'Rush att.',
        tooltip: 'Rushing attempts',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      rushing_yards: {
        id: 'rushing_yards',
        numeric: true,
        label: 'Rush yards',
        tooltip: 'Rushing yards',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      rushing_yards_per_attempt: {
        id: 'rushing_yards_per_attempt',
        numeric: true,
        label: 'Rush yards per att.',
        tooltip: 'Rushing yards per attempt',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      rushing_touchdowns: {
        id: 'rushing_touchdowns',
        numeric: true,
        label: 'Rush TD',
        tooltip: 'Rushing touchdowns',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      rushing_long: {
        id: 'rushing_long',
        numeric: true,
        label: 'Rush long',
        tooltip: 'Rushing long',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      receptions: {
        id: 'receptions',
        numeric: true,
        label: 'Receptions',
        tooltip: '# of receptions',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      receiving_yards: {
        id: 'receiving_yards',
        numeric: true,
        label: 'Rec. yards',
        tooltip: 'Receiving yards',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      receiving_yards_per_reception: {
        id: 'receiving_yards_per_reception',
        numeric: true,
        label: 'Rec. yards per recep.',
        tooltip: 'Receiving yards per reception',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      receiving_touchdowns: {
        id: 'receiving_touchdowns',
        numeric: true,
        label: 'Rec. TD',
        tooltip: 'Receiving touchdowns',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      receiving_long: {
        id: 'receiving_long',
        numeric: true,
        label: 'Rec. long',
        tooltip: 'Receiving long',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'player', 'conference', 'transfer'],
        graphable: true,
      },
      // punt_returns: {
      //   id: 'punt_returns',
      //   numeric: true,
      //   label: 'Punt ret.',
      //   tooltip: 'Punt returns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // punt_return_yards: {
      //   id: 'punt_return_yards',
      //   numeric: true,
      //   label: 'Punt ret. yards',
      //   tooltip: 'Punt return yards',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // punt_return_yards_per_attempt: {
      //   id: 'punt_return_yards_per_attempt',
      //   numeric: true,
      //   label: 'Punt ret. yards per att.',
      //   tooltip: 'Punt return yards per attempt',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // punt_return_touchdowns: {
      //   id: 'punt_return_touchdowns',
      //   numeric: true,
      //   label: 'Punt ret. TD',
      //   tooltip: 'Punt return touchdowns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // punt_return_long: {
      //   id: 'punt_return_long',
      //   numeric: true,
      //   label: 'Punt ret. long',
      //   tooltip: 'Punt return long',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // kick_returns: {
      //   id: 'kick_returns',
      //   numeric: true,
      //   label: 'Kick ret.',
      //   tooltip: 'Kick returns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // kick_return_yards: {
      //   id: 'kick_return_yards',
      //   numeric: true,
      //   label: 'Kick ret. yards',
      //   tooltip: 'Kick return yards',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // kick_return_yards_per_attempt: {
      //   id: 'kick_return_yards_per_attempt',
      //   numeric: true,
      //   label: 'Kick ret. yards per att.',
      //   tooltip: 'Kick return yards per attempt',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // kick_return_touchdowns: {
      //   id: 'kick_return_touchdowns',
      //   numeric: true,
      //   label: 'Kick ret. TD',
      //   tooltip: 'Kick return touchdowns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // kick_return_long: {
      //   id: 'kick_return_long',
      //   numeric: true,
      //   label: 'Kick ret. long',
      //   tooltip: 'Kick return long',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // punts: {
      //   id: 'punts',
      //   numeric: true,
      //   label: 'Punts',
      //   tooltip: 'Punts',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // punt_yards: {
      //   id: 'punt_yards',
      //   numeric: true,
      //   label: 'Punt yards',
      //   tooltip: 'Punt yards',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // punt_average: {
      //   id: 'punt_average',
      //   numeric: true,
      //   label: 'Punt avg.',
      //   tooltip: 'Punt average',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // punt_long: {
      //   id: 'punt_long',
      //   numeric: true,
      //   label: 'Punt long',
      //   tooltip: 'Punt long',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // field_goals_attempted: {
      //   id: 'field_goals_attempted',
      //   numeric: true,
      //   label: 'FG att.',
      //   tooltip: 'Field goals attempted',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // field_goals_made: {
      //   id: 'field_goals_made',
      //   numeric: true,
      //   label: 'FGs',
      //   tooltip: 'Field goals made',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // field_goal_percentage: {
      //   id: 'field_goal_percentage',
      //   numeric: true,
      //   label: 'FG%',
      //   tooltip: 'Field goal percentage',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // field_goals_longest_made: {
      //   id: 'field_goals_longest_made',
      //   numeric: true,
      //   label: 'FG long',
      //   tooltip: 'Field goal longest made',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // extra_points_attempted: {
      //   id: 'extra_points_attempted',
      //   numeric: true,
      //   label: '2pt att.',
      //   tooltip: '2pt conversion attempts',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // extra_points_made: {
      //   id: 'extra_points_made',
      //   numeric: true,
      //   label: '2pt con.',
      //   tooltip: '2pt conversions',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // interceptions: {
      //   id: 'interceptions',
      //   numeric: true,
      //   label: 'Int.',
      //   tooltip: 'Interceptions',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // interception_return_yards: {
      //   id: 'interception_return_yards',
      //   numeric: true,
      //   label: 'Int. ret. yards',
      //   tooltip: 'Interceptions return yards',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // interception_return_touchdowns: {
      //   id: 'interception_return_touchdowns',
      //   numeric: true,
      //   label: 'Int. ret. TD',
      //   tooltip: 'Interceptions return touchdowns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // solo_tackles: {
      //   id: 'solo_tackles',
      //   numeric: true,
      //   label: 'Solo tackle',
      //   tooltip: 'Solo tackles',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // assisted_tackles: {
      //   id: 'assisted_tackles',
      //   numeric: true,
      //   label: 'Ast. tackle',
      //   tooltip: 'Assisted tackles',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // tackles_for_loss: {
      //   id: 'tackles_for_loss',
      //   numeric: true,
      //   label: 'Tackle for loss',
      //   tooltip: 'Tackles for loss',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // sacks: {
      //   id: 'sacks',
      //   numeric: true,
      //   label: 'Sacks',
      //   tooltip: 'Sacks',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // passes_defended: {
      //   id: 'passes_defended',
      //   numeric: true,
      //   label: 'Pass defended',
      //   tooltip: 'Passes defended',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // fumbles_recovered: {
      //   id: 'fumbles_recovered',
      //   numeric: true,
      //   label: 'Fumble rec.',
      //   tooltip: 'Fumbles recovered',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // fumble_return_touchdowns: {
      //   id: 'fumble_return_touchdowns',
      //   numeric: true,
      //   label: 'Fumble ret. TD',
      //   tooltip: 'Fumbles returned to touchdown',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // quarterback_hurries: {
      //   id: 'quarterback_hurries',
      //   numeric: true,
      //   label: 'QB hurry',
      //   tooltip: 'QB hurries',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // fumbles: {
      //   id: 'fumbles',
      //   numeric: true,
      //   label: 'Fumbles',
      //   tooltip: 'Fumbles',
      //   sort: 'lower',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      // fumbles_lost: {
      //   id: 'fumbles_lost',
      //   numeric: true,
      //   label: 'Fumbles lost',
      //   tooltip: 'Fumbles lost',
      //   sort: 'lower',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'player', 'conference', 'transfer'],
      //   graphable: true,
      // },
      yards_per_play: {
        id: 'yards_per_play',
        numeric: true,
        label: 'YPP',
        tooltip: 'Yards per play',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      points_per_play: {
        id: 'points_per_play',
        numeric: true,
        label: 'PPP',
        tooltip: 'Points per play',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      // successful_pass_plays: {
      //   id: 'successful_pass_plays',
      //   numeric: true,
      //   label: 'SPP',
      //   tooltip: 'Successful pass plays',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // successful_rush_plays: {
      //   id: 'successful_rush_plays',
      //   numeric: true,
      //   label: 'SRP',
      //   tooltip: 'Successful rush plays',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // offensive_dvoa: {
      //   id: 'offensive_dvoa',
      //   numeric: true,
      //   label: 'O-DVOA',
      //   tooltip: 'offensive_dvoa', // todo
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // defensive_dvoa: {
      //   id: 'defensive_dvoa',
      //   numeric: true,
      //   label: 'D-DVOA',
      //   tooltip: 'defensive_dvoa', // todo
      //   sort: 'higher', // todo
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // first_downs: {
      //   id: 'first_downs',
      //   numeric: true,
      //   label: '1st downs',
      //   tooltip: '1st downs',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // third_down_conversions: {
      //   id: 'third_down_conversions',
      //   numeric: true,
      //   label: '3rd down conv.',
      //   tooltip: '3rd down conversion',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // third_down_attempts: {
      //   id: 'third_down_attempts',
      //   numeric: true,
      //   label: '3rd down att.',
      //   tooltip: '3rd down attempts',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // fourth_down_conversions: {
      //   id: 'fourth_down_conversions',
      //   numeric: true,
      //   label: '4rd down conv.',
      //   tooltip: '4rd down conversion',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // fourth_down_attempts: {
      //   id: 'fourth_down_attempts',
      //   numeric: true,
      //   label: '4rd down att.',
      //   tooltip: '4rd down attempts',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // time_of_possession_seconds: {
      //   id: 'time_of_possession_seconds',
      //   numeric: true,
      //   label: 'ToP',
      //   tooltip: 'Time of possession in seconds',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      opponent_yards_per_play: {
        id: 'opponent_yards_per_play',
        numeric: true,
        label: 'Opp. YPP',
        tooltip: 'Opponent Yards per play',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_points_per_play: {
        id: 'opponent_points_per_play',
        numeric: true,
        label: 'Opp. PPP',
        tooltip: 'Opponent Points per play',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      // opponent_successful_pass_plays: {
      //   id: 'opponent_successful_pass_plays',
      //   numeric: true,
      //   label: 'Opp. SPP',
      //   tooltip: 'Opponent Successful pass plays',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_successful_rush_plays: {
      //   id: 'opponent_successful_rush_plays',
      //   numeric: true,
      //   label: 'Opp. SRP',
      //   tooltip: 'Opponent Successful rush plays',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_offensive_dvoa: {
      //   id: 'opponent_offensive_dvoa',
      //   numeric: true,
      //   label: 'Opp. O-DVOA',
      //   tooltip: 'Opponent offensive_dvoa', // todo
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_defensive_dvoa: {
      //   id: 'opponent_defensive_dvoa',
      //   numeric: true,
      //   label: 'Opp. D-DVOA',
      //   tooltip: 'Opponent defensive_dvoa', // todo
      //   sort: 'higher', // todo
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_first_downs: {
      //   id: 'opponent_first_downs',
      //   numeric: true,
      //   label: 'Opp. 1st downs',
      //   tooltip: 'Opponent 1st downs',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_third_down_conversions: {
      //   id: 'opponent_third_down_conversions',
      //   numeric: true,
      //   label: 'Opp. 3rd down conv.',
      //   tooltip: 'Opponent 3rd down conversion',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_third_down_attempts: {
      //   id: 'opponent_third_down_attempts',
      //   numeric: true,
      //   label: 'Opp. 3rd down att.',
      //   tooltip: 'Opponent 3rd down attempts',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_fourth_down_conversions: {
      //   id: 'opponent_fourth_down_conversions',
      //   numeric: true,
      //   label: 'Opp. 4rd down conv.',
      //   tooltip: 'Opponent 4rd down conversion',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_fourth_down_attempts: {
      //   id: 'opponent_fourth_down_attempts',
      //   numeric: true,
      //   label: 'Opp. 4rd down att.',
      //   tooltip: 'Opponent 4rd down attempts',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_time_of_possession_seconds: {
      //   id: 'opponent_time_of_possession_seconds',
      //   numeric: true,
      //   label: 'Opp. ToP',
      //   tooltip: 'Opponent Time of possession in seconds',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      opponent_passing_attempts: {
        id: 'opponent_passing_attempts',
        numeric: true,
        label: 'Opp. Pass att.',
        tooltip: 'Opponent Passing attempts',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_completions: {
        id: 'opponent_passing_completions',
        numeric: true,
        label: 'Opp. Pass comp.',
        tooltip: 'Opponent Passing completions',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_yards: {
        id: 'opponent_passing_yards',
        numeric: true,
        label: 'Opp. Pass yards',
        tooltip: 'Opponent Passing yards',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_completion_percentage: {
        id: 'opponent_passing_completion_percentage',
        numeric: true,
        label: 'Opp. Pass comp. %',
        tooltip: 'Opponent Passing completions percentage',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_yards_per_attempt: {
        id: 'opponent_passing_yards_per_attempt',
        numeric: true,
        label: 'Opp. Pass yards per att.',
        tooltip: 'Opponent Passing yard per attempt',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_yards_per_completion: {
        id: 'opponent_passing_yards_per_completion',
        numeric: true,
        label: 'Opp. Pass yards per comp.',
        tooltip: 'Opponent Passing yards per completion',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_touchdowns: {
        id: 'opponent_passing_touchdowns',
        numeric: true,
        label: 'Opp. Pass TD',
        tooltip: 'Opponent Passing touchdowns',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_interceptions: {
        id: 'opponent_passing_interceptions',
        numeric: true,
        label: 'Opp. Pass int.',
        tooltip: 'Opponent Passing interceptions',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_rating_pro: {
        id: 'opponent_passing_rating_pro',
        numeric: true,
        label: 'Opp. QBR(p)',
        tooltip: 'Opponent Quarter back rating (pro)',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_rating_college: {
        id: 'opponent_passing_rating_college',
        numeric: true,
        label: 'Opp. QBR(c)',
        tooltip: 'Opponent Quarter back rating (college)',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_passing_long: {
        id: 'opponent_passing_long',
        numeric: true,
        label: 'Opp. Pass long',
        tooltip: 'Opponent Passing long',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_rushing_attempts: {
        id: 'opponent_rushing_attempts',
        numeric: true,
        label: 'Opp. Rush att.',
        tooltip: 'Opponent Rushing attempts',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_rushing_yards: {
        id: 'opponent_rushing_yards',
        numeric: true,
        label: 'Opp. Rush yards',
        tooltip: 'Opponent Rushing yards',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_rushing_yards_per_attempt: {
        id: 'opponent_rushing_yards_per_attempt',
        numeric: true,
        label: 'Opp. Rush yards per att.',
        tooltip: 'Opponent Rushing yards per attempt',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_rushing_touchdowns: {
        id: 'opponent_rushing_touchdowns',
        numeric: true,
        label: 'Opp. Rush TD',
        tooltip: 'Opponent Rushing touchdowns',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_rushing_long: {
        id: 'opponent_rushing_long',
        numeric: true,
        label: 'Opp. Rush long',
        tooltip: 'Opponent Rushing long',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_receptions: {
        id: 'opponent_receptions',
        numeric: true,
        label: 'Opp. Receptions',
        tooltip: 'Opponent # of receptions',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_receiving_yards: {
        id: 'opponent_receiving_yards',
        numeric: true,
        label: 'Opp. Rec. yards',
        tooltip: 'Opponent Receiving yards',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_receiving_yards_per_reception: {
        id: 'opponent_receiving_yards_per_reception',
        numeric: true,
        label: 'Opp. Rec. yards per recep.',
        tooltip: 'Opponent Receiving yards per reception',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_receiving_touchdowns: {
        id: 'opponent_receiving_touchdowns',
        numeric: true,
        label: 'Opp. Rec. TD',
        tooltip: 'Opponent Receiving touchdowns',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      opponent_receiving_long: {
        id: 'opponent_receiving_long',
        numeric: true,
        label: 'Opp. Rec. long',
        tooltip: 'Opponent Receiving long',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['team', 'conference'],
        graphable: true,
      },
      // opponent_punt_returns: {
      //   id: 'opponent_punt_returns',
      //   numeric: true,
      //   label: 'Opp. Punt ret.',
      //   tooltip: 'Opponent Punt returns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_punt_return_yards: {
      //   id: 'opponent_punt_return_yards',
      //   numeric: true,
      //   label: 'Opp. Punt ret. yards',
      //   tooltip: 'Opponent Punt return yards',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_punt_return_yards_per_attempt: {
      //   id: 'opponent_punt_return_yards_per_attempt',
      //   numeric: true,
      //   label: 'Opp. Punt ret. yards per att.',
      //   tooltip: 'Opponent Punt return yards per attempt',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_punt_return_touchdowns: {
      //   id: 'opponent_punt_return_touchdowns',
      //   numeric: true,
      //   label: 'Opp. Punt ret. TD',
      //   tooltip: 'Opponent Punt return touchdowns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_punt_return_long: {
      //   id: 'opponent_punt_return_long',
      //   numeric: true,
      //   label: 'Opp. Punt ret. long',
      //   tooltip: 'Opponent Punt return long',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_kick_returns: {
      //   id: 'opponent_kick_returns',
      //   numeric: true,
      //   label: 'Opp. Kick ret.',
      //   tooltip: 'Opponent Kick returns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_kick_return_yards: {
      //   id: 'opponent_kick_return_yards',
      //   numeric: true,
      //   label: 'Opp. Kick ret. yards',
      //   tooltip: 'Opponent Kick return yards',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_kick_return_yards_per_attempt: {
      //   id: 'opponent_kick_return_yards_per_attempt',
      //   numeric: true,
      //   label: 'Opp. Kick ret. yards per att.',
      //   tooltip: 'Opponent Kick return yards per attempt',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_kick_return_touchdowns: {
      //   id: 'opponent_kick_return_touchdowns',
      //   numeric: true,
      //   label: 'Opp. Kick ret. TD',
      //   tooltip: 'Opponent Kick return touchdowns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_kick_return_long: {
      //   id: 'opponent_kick_return_long',
      //   numeric: true,
      //   label: 'Opp. Kick ret. long',
      //   tooltip: 'Opponent Kick return long',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_punts: {
      //   id: 'opponent_punts',
      //   numeric: true,
      //   label: 'Opp. Punts',
      //   tooltip: 'Opponent Punts',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_punt_yards: {
      //   id: 'opponent_punt_yards',
      //   numeric: true,
      //   label: 'Opp. Punt yards',
      //   tooltip: 'Opponent Punt yards',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_punt_average: {
      //   id: 'opponent_punt_average',
      //   numeric: true,
      //   label: 'Opp. Punt avg.',
      //   tooltip: 'Opponent Punt average',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_punt_long: {
      //   id: 'opponent_punt_long',
      //   numeric: true,
      //   label: 'Opp. Punt long',
      //   tooltip: 'Opponent Punt long',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_field_goals_attempted: {
      //   id: 'opponent_field_goals_attempted',
      //   numeric: true,
      //   label: 'Opp. FG att.',
      //   tooltip: 'Opponent Field goals attempted',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_field_goals_made: {
      //   id: 'opponent_field_goals_made',
      //   numeric: true,
      //   label: 'Opp. FGs',
      //   tooltip: 'Opponent Field goals made',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_field_goal_percentage: {
      //   id: 'opponent_field_goal_percentage',
      //   numeric: true,
      //   label: 'Opp. FG%',
      //   tooltip: 'Opponent Field goal percentage',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_field_goals_longest_made: {
      //   id: 'opponent_field_goals_longest_made',
      //   numeric: true,
      //   label: 'Opp. FG long',
      //   tooltip: 'Opponent Field goal longest made',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_extra_points_attempted: {
      //   id: 'opponent_extra_points_attempted',
      //   numeric: true,
      //   label: 'Opp. 2pt att.',
      //   tooltip: 'Opponent 2pt conversion attempts',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_extra_points_made: {
      //   id: 'opponent_extra_points_made',
      //   numeric: true,
      //   label: 'Opp. 2pt con.',
      //   tooltip: 'Opponent 2pt conversions',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_interceptions: {
      //   id: 'opponent_interceptions',
      //   numeric: true,
      //   label: 'Opp. Int.',
      //   tooltip: 'Opponent Interceptions',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_interception_return_yards: {
      //   id: 'opponent_interception_return_yards',
      //   numeric: true,
      //   label: 'Opp. Int. ret. yards',
      //   tooltip: 'Opponent Interceptions return yards',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_interception_return_touchdowns: {
      //   id: 'opponent_interception_return_touchdowns',
      //   numeric: true,
      //   label: 'Opp. Int. ret. TD',
      //   tooltip: 'Opponent Interceptions return touchdowns',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_solo_tackles: {
      //   id: 'opponent_solo_tackles',
      //   numeric: true,
      //   label: 'Opp. Solo tackle',
      //   tooltip: 'Opponent Solo tackles',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_assisted_tackles: {
      //   id: 'opponent_assisted_tackles',
      //   numeric: true,
      //   label: 'Opp. Ast. tackle',
      //   tooltip: 'Opponent Assisted tackles',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_tackles_for_loss: {
      //   id: 'opponent_tackles_for_loss',
      //   numeric: true,
      //   label: 'Opp. Tackle for loss',
      //   tooltip: 'Opponent Tackles for loss',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_sacks: {
      //   id: 'opponent_sacks',
      //   numeric: true,
      //   label: 'Opp. Sacks',
      //   tooltip: 'Opponent Sacks',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_passes_defended: {
      //   id: 'opponent_passes_defended',
      //   numeric: true,
      //   label: 'Opp. Pass defended',
      //   tooltip: 'Opponent Passes defended',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_fumbles_recovered: {
      //   id: 'opponent_fumbles_recovered',
      //   numeric: true,
      //   label: 'Opp. Fumble rec.',
      //   tooltip: 'Opponent Fumbles recovered',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_fumble_return_touchdowns: {
      //   id: 'opponent_fumble_return_touchdowns',
      //   numeric: true,
      //   label: 'Opp. Fumble ret. TD',
      //   tooltip: 'Opponent Fumbles returned to touchdown',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_quarterback_hurries: {
      //   id: 'opponent_quarterback_hurries',
      //   numeric: true,
      //   label: 'Opp. QB hurry',
      //   tooltip: 'Opponent QB hurries',
      //   sort: 'higher',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_fumbles: {
      //   id: 'opponent_fumbles',
      //   numeric: true,
      //   label: 'Opp. Fumbles',
      //   tooltip: 'Opponent Fumbles',
      //   sort: 'lower',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      // opponent_fumbles_lost: {
      //   id: 'opponent_fumbles_lost',
      //   numeric: true,
      //   label: 'Opp. Fumbles lost',
      //   tooltip: 'Opponent Fumbles lost',
      //   sort: 'lower',
      //   organization_ids: [Organization.getCFBID()],
      //   views: ['team', 'conference'],
      //   graphable: true,
      // },
      passing_attempts_per_game: {
        id: 'passing_attempts_per_game',
        numeric: true,
        label: 'Pass att. per game',
        tooltip: 'Passing attempts per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      passing_completions_per_game: {
        id: 'passing_completions_per_game',
        numeric: true,
        label: 'Pass comp. per game',
        tooltip: 'Passing completions per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      passing_yards_per_game: {
        id: 'passing_yards_per_game',
        numeric: true,
        label: 'Pass yards per game',
        tooltip: 'Passing yards per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      passing_touchdowns_per_game: {
        id: 'passing_touchdowns_per_game',
        numeric: true,
        label: 'Pass TD per game',
        tooltip: 'Passing touchdowns per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      passing_interceptions_per_game: {
        id: 'passing_interceptions_per_game',
        numeric: true,
        label: 'Pass int. per game',
        tooltip: 'Passing interceptions per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      rushing_attempts_per_game: {
        id: 'rushing_attempts_per_game',
        numeric: true,
        label: 'Rush att. per game',
        tooltip: 'Rushing attempts per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      rushing_yards_per_game: {
        id: 'rushing_yards_per_game',
        numeric: true,
        label: 'Rush yards per game',
        tooltip: 'Rushing yards per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      rushing_touchdowns_per_game: {
        id: 'rushing_touchdowns_per_game',
        numeric: true,
        label: 'Rush TD per game',
        tooltip: 'Rushing touchdowns per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      receptions_per_game: {
        id: 'receptions_per_game',
        numeric: true,
        label: 'Receptions per game',
        tooltip: '# of receptions per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      receiving_yards_per_game: {
        id: 'receiving_yards_per_game',
        numeric: true,
        label: 'Rec. yards per game',
        tooltip: 'Receiving yards per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      receiving_touchdowns_per_game: {
        id: 'receiving_touchdowns_per_game',
        numeric: true,
        label: 'Rec. TD per game',
        tooltip: 'Receiving touchdowns per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      punt_returns_per_game: {
        id: 'punt_returns_per_game',
        numeric: true,
        label: 'Punt ret. per game',
        tooltip: 'Punt returns per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      punt_return_yards_per_game: {
        id: 'punt_return_yards_per_game',
        numeric: true,
        label: 'Punt ret. yards per game',
        tooltip: 'Punt return yards per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      punt_return_touchdowns_per_game: {
        id: 'punt_return_touchdowns_per_game',
        numeric: true,
        label: 'Punt ret. TD per game',
        tooltip: 'Punt return touchdowns per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      kick_returns_per_game: {
        id: 'kick_returns_per_game',
        numeric: true,
        label: 'Kick ret. per game',
        tooltip: 'Kick returns per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      kick_return_yards_per_game: {
        id: 'kick_return_yards_per_game',
        numeric: true,
        label: 'Kick ret. yards per game',
        tooltip: 'Kick return yards per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      kick_return_touchdowns_per_game: {
        id: 'kick_return_touchdowns_per_game',
        numeric: true,
        label: 'Kick ret. TD per game',
        tooltip: 'Kick return touchdowns per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      punts_per_game: {
        id: 'punts_per_game',
        numeric: true,
        label: 'Punts per game',
        tooltip: 'Punts per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      punt_yards_per_game: {
        id: 'punt_yards_per_game',
        numeric: true,
        label: 'Punt yards per game',
        tooltip: 'Punt yards per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      field_goals_attempted_per_game: {
        id: 'field_goals_attempted_per_game',
        numeric: true,
        label: 'FG att. per game',
        tooltip: 'Field goals attempted per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      field_goals_made_per_game: {
        id: 'field_goals_made_per_game',
        numeric: true,
        label: 'FGs per game',
        tooltip: 'Field goals made per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      interceptions_per_game: {
        id: 'interceptions_per_game',
        numeric: true,
        label: 'Int. per game',
        tooltip: 'Interceptions per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      sacks_per_game: {
        id: 'sacks_per_game',
        numeric: true,
        label: 'Sacks per game',
        tooltip: 'Sacks per game',
        sort: 'higher',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
      fumbles_per_game: {
        id: 'fumbles_per_game',
        numeric: true,
        label: 'Fumbles per game',
        tooltip: 'Fumbles per game',
        sort: 'lower',
        organization_ids: [Organization.getCFBID()],
        views: ['player'],
        graphable: true,
      },
    };

    for (const key in columns) {
      if (
        !columns[key].organization_ids.includes(organization_id) ||
        !columns[key].views.includes(view) ||
        (graphable !== undefined && graphable !== columns[key].graphable) ||
        (disabled !== undefined && 'disabled' in columns[key] && disabled !== columns[key].disabled)
      ) {
        delete columns[key];
      }
    }

    return columns;
  }
}

export default TableColumns;
