/* eslint-disable no-nested-ternary */
import Organization from '@/components/helpers/Organization';
import { RankingColumns } from '@/types/general';


export const getHeaderColumns = ({ organization_id, view }: {view: string, organization_id: string}) => {
  const headCells: RankingColumns = {
    rank: {
      id: 'rank',
      numeric: true,
      label: 'Rk',
      tooltip: 'srating.io Rank',
      sticky: true,
      disabled: true,
      sort: 'lower',
    },
    name: {
      id: 'name',
      numeric: false,
      label: (view === 'player' || view === 'transfer' ? 'Player' : (view === 'conference' ? 'Conference' : (view === 'coach' ? 'Coach' : 'Team'))),
      tooltip: (view === 'player' || view === 'transfer' ? 'Player name' : (view === 'conference' ? 'Conference name' : (view === 'coach' ? 'Coach name' : 'Team name'))),
      sticky: true,
      disabled: true,
    },
  };

  if (Organization.getCBBID() === organization_id) {
    if (view !== 'coach') {
      Object.assign(headCells, {
        field_goal: {
          id: 'field_goal',
          numeric: true,
          label: 'FG',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total field goals made in season' : 'Average field goals per game'),
          sort: 'higher',
        },
        field_goal_attempts: {
          id: 'field_goal_attempts',
          numeric: true,
          label: 'FGA',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total field goal attempts in season' : 'Average field goal attempts per game'),
          sort: 'higher',
        },
        field_goal_percentage: {
          id: 'field_goal_percentage',
          numeric: true,
          label: 'FG%',
          tooltip: 'Field goal percentage',
          sort: 'higher',
        },
        two_point_field_goal: {
          id: 'two_point_field_goal',
          numeric: true,
          label: '2FG',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total two point field goals made in season' : 'Average two point field goals per game'),
          sort: 'higher',
        },
        two_point_field_goal_attempts: {
          id: 'two_point_field_goal_attempts',
          numeric: true,
          label: '2FGA',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total two point field goal attempts in season' : 'Average two point field goal attempts per game'),
          sort: 'higher',
        },
        two_point_field_goal_percentage: {
          id: 'two_point_field_goal_percentage',
          numeric: true,
          label: '2FG%',
          tooltip: 'Two point field goal percentage',
          sort: 'higher',
        },
        three_point_field_goal: {
          id: 'three_point_field_goal',
          numeric: true,
          label: '3FG',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total three point field goals made in season' : 'Average three point field goals per game'),
          sort: 'higher',
        },
        three_point_field_goal_attempts: {
          id: 'three_point_field_goal_attempts',
          numeric: true,
          label: '3FGA',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total three field goal attempts in season' : 'Average three field goal attempts per game'),
          sort: 'higher',
        },
        three_point_field_goal_percentage: {
          id: 'three_point_field_goal_percentage',
          numeric: true,
          label: '3FG%',
          tooltip: 'Three field goal percentage',
          sort: 'higher',
        },
        free_throws: {
          id: 'free_throws',
          numeric: true,
          label: 'FT',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total free throws made in season' : 'Average free throws per game'),
          sort: 'higher',
        },
        free_throw_attempts: {
          id: 'free_throw_attempts',
          numeric: true,
          label: 'FTA',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total free throw attempts in season' : 'Average free throw attempts per game'),
          sort: 'higher',
        },
        free_throw_percentage: {
          id: 'free_throw_percentage',
          numeric: true,
          label: 'FT%',
          tooltip: 'Free throw percentage',
          sort: 'higher',
        },
        offensive_rebounds: {
          id: 'offensive_rebounds',
          numeric: true,
          label: 'ORB',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total offensive rebounds in season' : 'Average offensive rebounds per game'),
          sort: 'higher',
        },
        defensive_rebounds: {
          id: 'defensive_rebounds',
          numeric: true,
          label: 'DRB',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total defensive rebounds in season' : 'Average defensive rebounds per game'),
          sort: 'higher',
        },
        total_rebounds: {
          id: 'total_rebounds',
          numeric: true,
          label: 'TRB',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total rebounds in season' : 'Average total rebounds per game'),
          sort: 'higher',
        },
        assists: {
          id: 'assists',
          numeric: true,
          label: 'AST',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total assists in season' : 'Average assists per game'),
          sort: 'higher',
        },
        steals: {
          id: 'steals',
          numeric: true,
          label: 'STL',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total steals in season' : 'Average steals per game'),
          sort: 'higher',
        },
        blocks: {
          id: 'blocks',
          numeric: true,
          label: 'BLK',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total blocks in season' : 'Average blocks per game'),
          sort: 'higher',
        },
        turnovers: {
          id: 'turnovers',
          numeric: true,
          label: 'TOV',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total turnovers in season' : 'Average turnovers per game'),
          sort: 'lower',
        },
        fouls: {
          id: 'fouls',
          numeric: true,
          label: 'PF',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total fouls in season' : 'Average fouls per game'),
          sort: 'lower',
        },
        points: {
          id: 'points',
          numeric: true,
          label: 'PTS',
          tooltip: (view === 'player' || view === 'transfer' ? 'Total points in season' : 'Average points per game'),
          sort: 'higher',
        },
        offensive_rating: {
          id: 'offensive_rating',
          numeric: true,
          label: 'ORT',
          tooltip: 'Offensive rating ((PTS / Poss) * 100)',
          sort: 'higher',
        },
        defensive_rating: {
          id: 'defensive_rating',
          numeric: true,
          label: 'DRT',
          tooltip: 'Defensive rating ((Opp. PTS / Opp. Poss) * 100)',
          sort: 'lower',
        },
        efficiency_rating: {
          id: 'efficiency_rating',
          numeric: true,
          label: (view === 'team' ? 'EM' : 'ERT'),
          tooltip: (view === 'team' ? 'Efficiency margin (Offensive rating - Defensive rating)' : 'Efficiency rating'),
          sort: 'higher',
        },
      });
    }
    if (view === 'team') {
      Object.assign(headCells, {
        conference_code: {
          id: 'conference_code',
          numeric: false,
          label: 'Conf.',
          tooltip: 'Conference',
        },
        ap_rank: {
          id: 'ap_rank',
          numeric: true,
          label: 'AP',
          tooltip: 'Associated Press rank',
          sort: 'lower',
        },
        wins: {
          id: 'wins',
          numeric: false,
          label: 'W/L',
          tooltip: 'Win/Loss',
          sort: 'higher',
        },
        conf_record: {
          id: 'conf_record',
          numeric: false,
          label: 'CR',
          tooltip: 'Conference Record Win/Loss',
          sort: 'higher',
        },
        neutralwins: {
          id: 'neutralwins',
          numeric: true,
          label: 'Neut. wins',
          tooltip: 'Neutral wins',
          sort: 'higher',
        },
        neutrallosses: {
          id: 'neutrallosses',
          numeric: true,
          label: 'Neut. losses',
          tooltip: 'Neutral losses',
          sort: 'lower',
        },
        homewins: {
          id: 'homewins',
          numeric: true,
          label: 'Home wins',
          tooltip: 'Home wins',
          sort: 'higher',
        },
        homelosses: {
          id: 'homelosses',
          numeric: true,
          label: 'Home losses',
          tooltip: 'Home losses',
          sort: 'lower',
        },
        roadwins: {
          id: 'roadwins',
          numeric: true,
          label: 'Road wins',
          tooltip: 'Road wins',
          sort: 'higher',
        },
        roadlosses: {
          id: 'roadlosses',
          numeric: true,
          label: 'Road losses',
          tooltip: 'Road losses',
          sort: 'lower',
        },
        streak: {
          id: 'streak',
          numeric: true,
          label: 'Streak',
          tooltip: 'Number of wins or losses in a row (negative for loss)',
          sort: 'higher',
        },
        win_margin: {
          id: 'win_margin',
          numeric: true,
          label: 'Win margin',
          tooltip: 'Win margin',
          sort: 'higher',
        },
        loss_margin: {
          id: 'loss_margin',
          numeric: true,
          label: 'Loss margin',
          tooltip: 'Loss margin',
          sort: 'lower',
        },
        confwin_margin: {
          id: 'confwin_margin',
          numeric: true,
          label: 'C Win margin',
          tooltip: 'Conference Win margin',
          sort: 'higher',
        },
        confloss_margin: {
          id: 'confloss_margin',
          numeric: true,
          label: 'C Loss margin',
          tooltip: 'Conference Loss margin',
          sort: 'lower',
        },
        kenpom_rank: {
          id: 'kenpom_rank',
          numeric: true,
          label: 'KP',
          tooltip: 'kenpom.com rank',
          sort: 'lower',
        },
        srs_rank: {
          id: 'srs_rank',
          numeric: true,
          label: 'SRS',
          tooltip: 'Simple rating system rank',
          sort: 'lower',
        },
        net_rank: {
          id: 'net_rank',
          numeric: true,
          label: 'NET',
          tooltip: 'NET rank',
          sort: 'lower',
        },
        elo: {
          id: 'elo',
          numeric: true,
          label: 'SR',
          tooltip: 'srating.io ELO rating',
          sort: 'higher',
        },
        coaches_rank: {
          id: 'coaches_rank',
          numeric: true,
          label: 'Coaches',
          tooltip: 'Coaches poll rank',
          sort: 'lower',
        },
        possessions: {
          id: 'possessions',
          numeric: true,
          label: 'Poss.',
          tooltip: 'Average possessions per game',
          sort: 'higher',
        },
        pace: {
          id: 'pace',
          numeric: true,
          label: 'Pace',
          tooltip: 'Average pace per game',
          sort: 'higher',
        },
        adjusted_efficiency_rating: {
          id: 'adjusted_efficiency_rating',
          numeric: true,
          label: 'aEM',
          tooltip: 'Adjusted Efficiency margin (Offensive rating - Defensive rating) + aSOS',
          sort: 'higher',
        },
        opponent_offensive_rating: {
          id: 'opponent_offensive_rating',
          numeric: true,
          label: 'oORT',
          tooltip: 'Opponent average Offensive rating',
          sort: 'higher',
        },
        opponent_defensive_rating: {
          id: 'opponent_defensive_rating',
          numeric: true,
          label: 'oDRT',
          tooltip: 'Opponent average Defensive rating ',
          sort: 'lower',
        },
        opponent_efficiency_rating: {
          id: 'opponent_efficiency_rating',
          numeric: true,
          label: 'aSOS',
          tooltip: 'Strength of schedule (Opponent Efficiency margin (oORT - oDRT))',
          sort: 'higher',
        },
        elo_sos: {
          id: 'elo_sos',
          numeric: true,
          label: 'eSOS',
          tooltip: 'Strength of schedule (opponent elo)',
          sort: 'higher',
        },
        opponent_field_goal: {
          id: 'opponent_field_goal',
          numeric: true,
          label: 'Opp. FG',
          tooltip: 'Opponent average field goals per game',
          sort: 'lower',
        },
        opponent_field_goal_attempts: {
          id: 'opponent_field_goal_attempts',
          numeric: true,
          label: 'Opp. FGA',
          tooltip: 'Opponent average field goal attempts per game',
          sort: 'lower',
        },
        opponent_field_goal_percentage: {
          id: 'opponent_field_goal_percentage',
          numeric: true,
          label: 'Opp. FG%',
          tooltip: 'Opponent average field goal percentage per game',
          sort: 'lower',
        },
        opponent_two_point_field_goal: {
          id: 'opponent_two_point_field_goal',
          numeric: true,
          label: 'Opp. 2FG',
          tooltip: 'Opponent average two point field goals per game',
          sort: 'lower',
        },
        opponent_two_point_field_goal_attempts: {
          id: 'opponent_two_point_field_goal_attempts',
          numeric: true,
          label: 'Opp. 2FGA',
          tooltip: 'Opponent average two point field goal attempts per game',
          sort: 'lower',
        },
        opponent_two_point_field_goal_percentage: {
          id: 'opponent_two_point_field_goal_percentage',
          numeric: true,
          label: 'Opp. 2FG%',
          tooltip: 'Opponent average two point field goal percentage per game',
          sort: 'lower',
        },
        opponent_three_point_field_goal: {
          id: 'opponent_three_point_field_goal',
          numeric: true,
          label: 'Opp. 3FG',
          tooltip: 'Opponent average three point field goals per game',
          sort: 'lower',
        },
        opponent_three_point_field_goal_attempts: {
          id: 'opponent_three_point_field_goal_attempts',
          numeric: true,
          label: 'Opp. 3FGA',
          tooltip: 'Opponent average three point field goal attempts per game',
          sort: 'lower',
        },
        opponent_three_point_field_goal_percentage: {
          id: 'opponent_three_point_field_goal_percentage',
          numeric: true,
          label: 'Opp. 3FG%',
          tooltip: 'Opponent average three point field goal percentage per game',
          sort: 'lower',
        },
        opponent_free_throws: {
          id: 'opponent_free_throws',
          numeric: true,
          label: 'Opp. FT',
          tooltip: 'Opponent average free throws per game',
          sort: 'lower',
        },
        opponent_free_throw_attempts: {
          id: 'opponent_free_throw_attempts',
          numeric: true,
          label: 'Opp. FTA',
          tooltip: 'Opponent average free throw attempts per game',
          sort: 'lower',
        },
        opponent_free_throw_percentage: {
          id: 'opponent_free_throw_percentage',
          numeric: true,
          label: 'Opp. FT%',
          tooltip: 'Opponent average free throw percentage per game',
          sort: 'lower',
        },
        opponent_offensive_rebounds: {
          id: 'opponent_offensive_rebounds',
          numeric: true,
          label: 'Opp. ORB',
          tooltip: 'Opponent average offensive rebounds per game',
          sort: 'lower',
        },
        opponent_defensive_rebounds: {
          id: 'opponent_defensive_rebounds',
          numeric: true,
          label: 'Opp. DRB',
          tooltip: 'Opponent average defensive rebounds per game',
          sort: 'lower',
        },
        opponent_total_rebounds: {
          id: 'opponent_total_rebounds',
          numeric: true,
          label: 'Opp. TRB',
          tooltip: 'Opponent average total rebounds per game',
          sort: 'lower',
        },
        opponent_assists: {
          id: 'opponent_assists',
          numeric: true,
          label: 'Opp. AST',
          tooltip: 'Opponent average assists per game',
          sort: 'lower',
        },
        opponent_steals: {
          id: 'opponent_steals',
          numeric: true,
          label: 'Opp. STL',
          tooltip: 'Opponent average steals per game',
          sort: 'lower',
        },
        opponent_blocks: {
          id: 'opponent_blocks',
          numeric: true,
          label: 'Opp. BLK',
          tooltip: 'Opponent average blocks per game',
          sort: 'lower',
        },
        opponent_turnovers: {
          id: 'opponent_turnovers',
          numeric: true,
          label: 'Opp. TOV',
          tooltip: 'Opponent average turnovers per game',
          sort: 'higher',
        },
        opponent_fouls: {
          id: 'opponent_fouls',
          numeric: true,
          label: 'Opp. PF',
          tooltip: 'Opponent average fouls per game',
          sort: 'higher',
        },
        opponent_points: {
          id: 'opponent_points',
          numeric: true,
          label: 'Opp. PTS',
          tooltip: 'Opponent average points per game',
          sort: 'lower',
        },
        opponent_possessions: {
          id: 'opponent_possessions',
          numeric: true,
          label: 'Opp. Poss.',
          tooltip: 'Opponent average possessions per game',
          sort: 'lower',
        },
      });
    } else if (view === 'player' || view === 'transfer') {
      if (view === 'transfer') {
        Object.assign(headCells, {
          committed: {
            id: 'committed',
            numeric: false,
            label: 'Committed',
            tooltip: 'Player committed',
          },
          committed_team_name: {
            id: 'committed_team_name',
            numeric: false,
            label: 'New team',
            tooltip: 'New (committed) team name',
          },
        });
      }
      Object.assign(headCells, {
        team_name: {
          id: 'team_name',
          numeric: false,
          label: (view === 'transfer' ? 'Prev. team' : 'Team'),
          tooltip: (view === 'transfer' ? 'Previous team name' : 'Team name'),
        },
        games: {
          id: 'games',
          numeric: false,
          label: 'G',
          tooltip: 'Games played',
        },
        position: {
          id: 'position',
          numeric: false,
          label: 'Position',
          tooltip: 'Player position',
        },
        number: {
          id: 'number',
          numeric: false,
          label: 'Number',
          tooltip: 'Jersey number',
        },
        height: {
          id: 'height',
          numeric: false,
          label: 'Height',
          tooltip: 'Player height',
        },
        minutes_played: {
          id: 'minutes_played',
          numeric: true,
          label: 'MP',
          tooltip: 'Total minutes played',
          sort: 'higher',
        },
        minutes_per_game: {
          id: 'minutes_per_game',
          numeric: true,
          label: 'MPG',
          tooltip: 'Minutes played per game',
          sort: 'higher',
        },
        points_per_game: {
          id: 'points_per_game',
          numeric: true,
          label: 'PPG',
          tooltip: 'Points per game',
          sort: 'higher',
        },
        offensive_rebounds_per_game: {
          id: 'offensive_rebounds_per_game',
          numeric: true,
          label: 'ORB-G',
          tooltip: 'Offensive rebounds per game',
          sort: 'higher',
        },
        defensive_rebounds_per_game: {
          id: 'defensive_rebounds_per_game',
          numeric: true,
          label: 'DRB-G',
          tooltip: 'Defensive rebounds per game',
          sort: 'higher',
        },
        total_rebounds_per_game: {
          id: 'total_rebounds_per_game',
          numeric: true,
          label: 'TRB-G',
          tooltip: 'Total rebounds per game',
          sort: 'higher',
        },
        assists_per_game: {
          id: 'assists_per_game',
          numeric: true,
          label: 'AST-G',
          tooltip: 'Assists per game',
          sort: 'higher',
        },
        steals_per_game: {
          id: 'steals_per_game',
          numeric: true,
          label: 'STL-G',
          tooltip: 'Steals per game',
          sort: 'higher',
        },
        blocks_per_game: {
          id: 'blocks_per_game',
          numeric: true,
          label: 'BLK-G',
          tooltip: 'Blocks per game',
          sort: 'higher',
        },
        turnovers_per_game: {
          id: 'turnovers_per_game',
          numeric: true,
          label: 'TO-G',
          tooltip: 'Blocks per game',
          sort: 'higher',
        },
        fouls_per_game: {
          id: 'fouls_per_game',
          numeric: true,
          label: 'PF-G',
          tooltip: 'Fouls per game',
          sort: 'higher',
        },
        player_efficiency_rating: {
          id: 'player_efficiency_rating',
          numeric: true,
          label: 'PER',
          tooltip: 'Player efficiency rating metric',
          sort: 'higher',
        },
        true_shooting_percentage: {
          id: 'true_shooting_percentage',
          numeric: true,
          label: 'TS%',
          tooltip: 'True shooting percentage, takes into account all field goals and free throws.',
          sort: 'higher',
        },
        effective_field_goal_percentage: {
          id: 'effective_field_goal_percentage',
          numeric: true,
          label: 'eFG%',
          tooltip: 'Effective field goal percentage, adjusted field goal % since 3 points greater than 2.',
          sort: 'higher',
        },
        offensive_rebound_percentage: {
          id: 'offensive_rebound_percentage',
          numeric: true,
          label: 'ORB%',
          tooltip: 'Offensive rebound percentage, estimate of % of offensive rebounds player had while on floor.',
          sort: 'higher',
        },
        defensive_rebound_percentage: {
          id: 'defensive_rebound_percentage',
          numeric: true,
          label: 'DRB%',
          tooltip: 'Defensive rebound percentage, estimate of % of defensive rebounds player had while on floor.',
          sort: 'higher',
        },
        total_rebound_percentage: {
          id: 'total_rebound_percentage',
          numeric: true,
          label: 'TRB%',
          tooltip: 'Total rebound percentage, estimate of % of total rebounds player had while on floor.',
          sort: 'higher',
        },
        assist_percentage: {
          id: 'assist_percentage',
          numeric: true,
          label: 'AST%',
          tooltip: 'Assist percentage, estimate of % of assists player had while on floor.',
          sort: 'higher',
        },
        steal_percentage: {
          id: 'steal_percentage',
          numeric: true,
          label: 'STL%',
          tooltip: 'Steal percentage, estimate of % of steals player had while on floor.',
          sort: 'higher',
        },
        block_percentage: {
          id: 'block_percentage',
          numeric: true,
          label: 'BLK%',
          tooltip: 'Block percentage, estimate of % of blocks player had while on floor.',
          sort: 'higher',
        },
        turnover_percentage: {
          id: 'turnover_percentage',
          numeric: true,
          label: 'TOV%',
          tooltip: 'Turnover percentage, estimate of % of turnovers player had while on floor.',
          sort: 'higher',
        },
        usage_percentage: {
          id: 'usage_percentage',
          numeric: true,
          label: 'USG%',
          tooltip: 'Usage percentage, estimate of % of plays ran through player while on floor.',
          sort: 'higher',
        },
      });
    } else if (view === 'conference') {
      Object.assign(headCells, {
        elo: {
          id: 'elo',
          numeric: true,
          label: 'SR',
          tooltip: 'srating.io ELO rating',
          sort: 'higher',
        },
        wins: {
          id: 'wins',
          numeric: false,
          label: 'Avg. W',
          tooltip: 'Average # of Wins',
          sort: 'higher',
        },
        losses: {
          id: 'losses',
          numeric: false,
          label: 'Avg. L',
          tooltip: 'Average # of Losses',
          sort: 'lower',
        },
        nonconfwins: {
          id: 'nonconfwins',
          numeric: false,
          label: 'NONC W',
          tooltip: 'Non-Conference Avg. # of Wins',
          sort: 'higher',
        },
        nonconflosses: {
          id: 'nonconflosses',
          numeric: false,
          label: 'NONC L',
          tooltip: 'Non-Conference Avg. # of Losses',
          sort: 'lower',
        },
        nonconfwin_margin: {
          id: 'nonconfwin_margin',
          numeric: false,
          label: 'NONC W Margin',
          tooltip: 'Non-Conference Avg. # of Win Margin',
          sort: 'higher',
        },
        nonconfloss_margin: {
          id: 'nonconfloss_margin',
          numeric: false,
          label: 'NONC L Margin',
          tooltip: 'Non-Conference Avg. # of Loss Margin',
          sort: 'lower',
        },
        possessions: {
          id: 'possessions',
          numeric: true,
          label: 'Poss.',
          tooltip: 'Average possessions per game',
          sort: 'higher',
        },
        pace: {
          id: 'pace',
          numeric: true,
          label: 'Pace',
          tooltip: 'Average pace per game',
          sort: 'higher',
        },
        adjusted_efficiency_rating: {
          id: 'adjusted_efficiency_rating',
          numeric: true,
          label: 'aEM',
          tooltip: 'Adjusted Efficiency margin (Offensive rating - Defensive rating) + aSOS',
          sort: 'higher',
        },
        opponent_offensive_rating: {
          id: 'opponent_offensive_rating',
          numeric: true,
          label: 'oORT',
          tooltip: 'Opponent average Offensive rating',
          sort: 'higher',
        },
        opponent_defensive_rating: {
          id: 'opponent_defensive_rating',
          numeric: true,
          label: 'oDRT',
          tooltip: 'Opponent average Defensive rating ',
          sort: 'lower',
        },
        opponent_efficiency_rating: {
          id: 'opponent_efficiency_rating',
          numeric: true,
          label: 'aSOS',
          tooltip: 'Strength of schedule (Opponent Efficiency margin (oORT - oDRT))',
          sort: 'higher',
        },
        elo_sos: {
          id: 'elo_sos',
          numeric: true,
          label: 'eSOS',
          tooltip: 'Strength of schedule (opponent elo)',
          sort: 'higher',
        },
        opponent_field_goal: {
          id: 'opponent_field_goal',
          numeric: true,
          label: 'Opp. FG',
          tooltip: 'Opponent average field goals per game',
          sort: 'lower',
        },
        opponent_field_goal_attempts: {
          id: 'opponent_field_goal_attempts',
          numeric: true,
          label: 'Opp. FGA',
          tooltip: 'Opponent average field goal attempts per game',
          sort: 'lower',
        },
        opponent_field_goal_percentage: {
          id: 'opponent_field_goal_percentage',
          numeric: true,
          label: 'Opp. FG%',
          tooltip: 'Opponent average field goal percentage per game',
          sort: 'lower',
        },
        opponent_two_point_field_goal: {
          id: 'opponent_two_point_field_goal',
          numeric: true,
          label: 'Opp. 2FG',
          tooltip: 'Opponent average two point field goals per game',
          sort: 'lower',
        },
        opponent_two_point_field_goal_attempts: {
          id: 'opponent_two_point_field_goal_attempts',
          numeric: true,
          label: 'Opp. 2FGA',
          tooltip: 'Opponent average two point field goal attempts per game',
          sort: 'lower',
        },
        opponent_two_point_field_goal_percentage: {
          id: 'opponent_two_point_field_goal_percentage',
          numeric: true,
          label: 'Opp. 2FG%',
          tooltip: 'Opponent average two point field goal percentage per game',
          sort: 'lower',
        },
        opponent_three_point_field_goal: {
          id: 'opponent_three_point_field_goal',
          numeric: true,
          label: 'Opp. 3FG',
          tooltip: 'Opponent average three point field goals per game',
          sort: 'lower',
        },
        opponent_three_point_field_goal_attempts: {
          id: 'opponent_three_point_field_goal_attempts',
          numeric: true,
          label: 'Opp. 3FGA',
          tooltip: 'Opponent average three point field goal attempts per game',
          sort: 'lower',
        },
        opponent_three_point_field_goal_percentage: {
          id: 'opponent_three_point_field_goal_percentage',
          numeric: true,
          label: 'Opp. 3FG%',
          tooltip: 'Opponent average three point field goal percentage per game',
          sort: 'lower',
        },
        opponent_free_throws: {
          id: 'opponent_free_throws',
          numeric: true,
          label: 'Opp. FT',
          tooltip: 'Opponent average free throws per game',
          sort: 'lower',
        },
        opponent_free_throw_attempts: {
          id: 'opponent_free_throw_attempts',
          numeric: true,
          label: 'Opp. FTA',
          tooltip: 'Opponent average free throw attempts per game',
          sort: 'lower',
        },
        opponent_free_throw_percentage: {
          id: 'opponent_free_throw_percentage',
          numeric: true,
          label: 'Opp. FT%',
          tooltip: 'Opponent average free throw percentage per game',
          sort: 'lower',
        },
        opponent_offensive_rebounds: {
          id: 'opponent_offensive_rebounds',
          numeric: true,
          label: 'Opp. ORB',
          tooltip: 'Opponent average offensive rebounds per game',
          sort: 'lower',
        },
        opponent_defensive_rebounds: {
          id: 'opponent_defensive_rebounds',
          numeric: true,
          label: 'Opp. DRB',
          tooltip: 'Opponent average defensive rebounds per game',
          sort: 'lower',
        },
        opponent_total_rebounds: {
          id: 'opponent_total_rebounds',
          numeric: true,
          label: 'Opp. TRB',
          tooltip: 'Opponent average total rebounds per game',
          sort: 'lower',
        },
        opponent_assists: {
          id: 'opponent_assists',
          numeric: true,
          label: 'Opp. AST',
          tooltip: 'Opponent average assists per game',
          sort: 'lower',
        },
        opponent_steals: {
          id: 'opponent_steals',
          numeric: true,
          label: 'Opp. STL',
          tooltip: 'Opponent average steals per game',
          sort: 'lower',
        },
        opponent_blocks: {
          id: 'opponent_blocks',
          numeric: true,
          label: 'Opp. BLK',
          tooltip: 'Opponent average blocks per game',
          sort: 'lower',
        },
        opponent_turnovers: {
          id: 'opponent_turnovers',
          numeric: true,
          label: 'Opp. TOV',
          tooltip: 'Opponent average turnovers per game',
          sort: 'higher',
        },
        opponent_fouls: {
          id: 'opponent_fouls',
          numeric: true,
          label: 'Opp. PF',
          tooltip: 'Opponent average fouls per game',
          sort: 'higher',
        },
        opponent_points: {
          id: 'opponent_points',
          numeric: true,
          label: 'Opp. PTS',
          tooltip: 'Opponent average points per game',
          sort: 'lower',
        },
        opponent_possessions: {
          id: 'opponent_possessions',
          numeric: true,
          label: 'Opp. Poss.',
          tooltip: 'Opponent average possessions per game',
          sort: 'lower',
        },
      });
    }
  }

  if (Organization.getCFBID() === organization_id) {
    if (view !== 'coach') {
      Object.assign(headCells, {
        points: {
          id: 'points',
          numeric: true,
          label: 'PTS',
          tooltip: 'Points',
          sort: 'higher',
        },
        passing_attempts: {
          id: 'passing_attempts',
          numeric: true,
          label: 'Pass att.',
          tooltip: 'Passing attempts',
          sort: 'higher',
        },
        passing_completions: {
          id: 'passing_completions',
          numeric: true,
          label: 'Pass comp.',
          tooltip: 'Passing completions',
          sort: 'higher',
        },
        passing_yards: {
          id: 'passing_yards',
          numeric: true,
          label: 'Pass yards',
          tooltip: 'Passing yards',
          sort: 'higher',
        },
        passing_completion_percentage: {
          id: 'passing_completion_percentage',
          numeric: true,
          label: 'Pass comp. %',
          tooltip: 'Passing completions percentage',
          sort: 'higher',
        },
        passing_yards_per_attempt: {
          id: 'passing_yards_per_attempt',
          numeric: true,
          label: 'Pass yards per att.',
          tooltip: 'Passing yard per attempt',
          sort: 'higher',
        },
        passing_yards_per_completion: {
          id: 'passing_yards_per_completion',
          numeric: true,
          label: 'Pass yards per comp.',
          tooltip: 'Passing yards per completion',
          sort: 'higher',
        },
        passing_touchdowns: {
          id: 'passing_touchdowns',
          numeric: true,
          label: 'Pass TD',
          tooltip: 'Passing touchdowns',
          sort: 'higher',
        },
        passing_interceptions: {
          id: 'passing_interceptions',
          numeric: true,
          label: 'Pass int.',
          tooltip: 'Passing interceptions',
          sort: 'higher',
        },
        passing_rating_pro: {
          id: 'passing_rating_pro',
          numeric: true,
          label: 'QBR(p)',
          tooltip: 'Quarter back rating (pro)',
          sort: 'higher',
        },
        passing_rating_college: {
          id: 'passing_rating_college',
          numeric: true,
          label: 'QBR(c)',
          tooltip: 'Quarter back rating (college)',
          sort: 'higher',
        },
        passing_long: {
          id: 'passing_long',
          numeric: true,
          label: 'Pass long',
          tooltip: 'Passing long',
          sort: 'higher',
        },
        rushing_attempts: {
          id: 'rushing_attempts',
          numeric: true,
          label: 'Rush att.',
          tooltip: 'Rushing attempts',
          sort: 'higher',
        },
        rushing_yards: {
          id: 'rushing_yards',
          numeric: true,
          label: 'Rush yards',
          tooltip: 'Rushing yards',
          sort: 'higher',
        },
        rushing_yards_per_attempt: {
          id: 'rushing_yards_per_attempt',
          numeric: true,
          label: 'Rush yards per att.',
          tooltip: 'Rushing yards per attempt',
          sort: 'higher',
        },
        rushing_touchdowns: {
          id: 'rushing_touchdowns',
          numeric: true,
          label: 'Rush TD',
          tooltip: 'Rushing touchdowns',
          sort: 'higher',
        },
        rushing_long: {
          id: 'rushing_long',
          numeric: true,
          label: 'Rush long',
          tooltip: 'Rushing long',
          sort: 'higher',
        },
        receptions: {
          id: 'receptions',
          numeric: true,
          label: 'Receptions',
          tooltip: '# of receptions',
          sort: 'higher',
        },
        receiving_yards: {
          id: 'receiving_yards',
          numeric: true,
          label: 'Rec. yards',
          tooltip: 'Recieving yards',
          sort: 'higher',
        },
        receiving_yards_per_reception: {
          id: 'receiving_yards_per_reception',
          numeric: true,
          label: 'Rec. yards per recep.',
          tooltip: 'Receiving yards per reception',
          sort: 'higher',
        },
        receiving_touchdowns: {
          id: 'receiving_touchdowns',
          numeric: true,
          label: 'Rec. TD',
          tooltip: 'Receiving touchdowns',
          sort: 'higher',
        },
        receiving_long: {
          id: 'receiving_long',
          numeric: true,
          label: 'Rec. long',
          tooltip: 'Receiving long',
          sort: 'higher',
        },
        // punt_returns: {
        //   id: 'punt_returns',
        //   numeric: true,
        //   label: 'Punt ret.',
        //   tooltip: 'Punt returns',
        //   sort: 'higher',
        // },
        // punt_return_yards: {
        //   id: 'punt_return_yards',
        //   numeric: true,
        //   label: 'Punt ret. yards',
        //   tooltip: 'Punt return yards',
        //   sort: 'higher',
        // },
        // punt_return_yards_per_attempt: {
        //   id: 'punt_return_yards_per_attempt',
        //   numeric: true,
        //   label: 'Punt ret. yards per att.',
        //   tooltip: 'Punt return yards per attempt',
        //   sort: 'higher',
        // },
        // punt_return_touchdowns: {
        //   id: 'punt_return_touchdowns',
        //   numeric: true,
        //   label: 'Punt ret. TD',
        //   tooltip: 'Punt return touchdowns',
        //   sort: 'higher',
        // },
        // punt_return_long: {
        //   id: 'punt_return_long',
        //   numeric: true,
        //   label: 'Punt ret. long',
        //   tooltip: 'Punt return long',
        //   sort: 'higher',
        // },
        // kick_returns: {
        //   id: 'kick_returns',
        //   numeric: true,
        //   label: 'Kick ret.',
        //   tooltip: 'Kick returns',
        //   sort: 'higher',
        // },
        // kick_return_yards: {
        //   id: 'kick_return_yards',
        //   numeric: true,
        //   label: 'Kick ret. yards',
        //   tooltip: 'Kick return yards',
        //   sort: 'higher',
        // },
        // kick_return_yards_per_attempt: {
        //   id: 'kick_return_yards_per_attempt',
        //   numeric: true,
        //   label: 'Kick ret. yards per att.',
        //   tooltip: 'Kick return yards per attempt',
        //   sort: 'higher',
        // },
        // kick_return_touchdowns: {
        //   id: 'kick_return_touchdowns',
        //   numeric: true,
        //   label: 'Kick ret. TD',
        //   tooltip: 'Kick return touchdowns',
        //   sort: 'higher',
        // },
        // kick_return_long: {
        //   id: 'kick_return_long',
        //   numeric: true,
        //   label: 'Kick ret. long',
        //   tooltip: 'Kick return long',
        //   sort: 'higher',
        // },
        // punts: {
        //   id: 'punts',
        //   numeric: true,
        //   label: 'Punts',
        //   tooltip: 'Punts',
        //   sort: 'higher',
        // },
        // punt_yards: {
        //   id: 'punt_yards',
        //   numeric: true,
        //   label: 'Punt yards',
        //   tooltip: 'Punt yards',
        //   sort: 'higher',
        // },
        // punt_average: {
        //   id: 'punt_average',
        //   numeric: true,
        //   label: 'Punt avg.',
        //   tooltip: 'Punt average',
        //   sort: 'higher',
        // },
        // punt_long: {
        //   id: 'punt_long',
        //   numeric: true,
        //   label: 'Punt long',
        //   tooltip: 'Punt long',
        //   sort: 'higher',
        // },
        // field_goals_attempted: {
        //   id: 'field_goals_attempted',
        //   numeric: true,
        //   label: 'FG att.',
        //   tooltip: 'Field goals attempted',
        //   sort: 'higher',
        // },
        // field_goals_made: {
        //   id: 'field_goals_made',
        //   numeric: true,
        //   label: 'FGs',
        //   tooltip: 'Field goals made',
        //   sort: 'higher',
        // },
        // field_goal_percentage: {
        //   id: 'field_goal_percentage',
        //   numeric: true,
        //   label: 'FG%',
        //   tooltip: 'Field goal percentage',
        //   sort: 'higher',
        // },
        // field_goals_longest_made: {
        //   id: 'field_goals_longest_made',
        //   numeric: true,
        //   label: 'FG long',
        //   tooltip: 'Field goal longest made',
        //   sort: 'higher',
        // },
        // extra_points_attempted: {
        //   id: 'extra_points_attempted',
        //   numeric: true,
        //   label: '2pt att.',
        //   tooltip: '2pt conversion attempts',
        //   sort: 'higher',
        // },
        // extra_points_made: {
        //   id: 'extra_points_made',
        //   numeric: true,
        //   label: '2pt con.',
        //   tooltip: '2pt conversions',
        //   sort: 'higher',
        // },
        // interceptions: {
        //   id: 'interceptions',
        //   numeric: true,
        //   label: 'Int.',
        //   tooltip: 'Interceptions',
        //   sort: 'higher',
        // },
        // interception_return_yards: {
        //   id: 'interception_return_yards',
        //   numeric: true,
        //   label: 'Int. ret. yards',
        //   tooltip: 'Interceptions return yards',
        //   sort: 'higher',
        // },
        // interception_return_touchdowns: {
        //   id: 'interception_return_touchdowns',
        //   numeric: true,
        //   label: 'Int. ret. TD',
        //   tooltip: 'Interceptions return touchdowns',
        //   sort: 'higher',
        // },
        // solo_tackles: {
        //   id: 'solo_tackles',
        //   numeric: true,
        //   label: 'Solo tackle',
        //   tooltip: 'Solo tackles',
        //   sort: 'higher',
        // },
        // assisted_tackles: {
        //   id: 'assisted_tackles',
        //   numeric: true,
        //   label: 'Ast. tackle',
        //   tooltip: 'Assisted tackles',
        //   sort: 'higher',
        // },
        // tackles_for_loss: {
        //   id: 'tackles_for_loss',
        //   numeric: true,
        //   label: 'Tackle for loss',
        //   tooltip: 'Tackles for loss',
        //   sort: 'higher',
        // },
        // sacks: {
        //   id: 'sacks',
        //   numeric: true,
        //   label: 'Sacks',
        //   tooltip: 'Sacks',
        //   sort: 'higher',
        // },
        // passes_defended: {
        //   id: 'passes_defended',
        //   numeric: true,
        //   label: 'Pass defended',
        //   tooltip: 'Passes defended',
        //   sort: 'higher',
        // },
        // fumbles_recovered: {
        //   id: 'fumbles_recovered',
        //   numeric: true,
        //   label: 'Fumble rec.',
        //   tooltip: 'Fumbles recovered',
        //   sort: 'higher',
        // },
        // fumble_return_touchdowns: {
        //   id: 'fumble_return_touchdowns',
        //   numeric: true,
        //   label: 'Fumble ret. TD',
        //   tooltip: 'Fumbles returned to touchdown',
        //   sort: 'higher',
        // },
        // quarterback_hurries: {
        //   id: 'quarterback_hurries',
        //   numeric: true,
        //   label: 'QB hurry',
        //   tooltip: 'QB hurries',
        //   sort: 'higher',
        // },
        // fumbles: {
        //   id: 'fumbles',
        //   numeric: true,
        //   label: 'Fumbles',
        //   tooltip: 'Fumbles',
        //   sort: 'lower',
        // },
        // fumbles_lost: {
        //   id: 'fumbles_lost',
        //   numeric: true,
        //   label: 'Fumbles lost',
        //   tooltip: 'Fumbles lost',
        //   sort: 'lower',
        // },
      });
    }
    if (view === 'team' || view === 'conference') {
      Object.assign(headCells, {
        conference_code: {
          id: 'conference_code',
          numeric: false,
          label: 'Conf.',
          tooltip: 'Conference',
        },
        wins: {
          id: 'wins',
          numeric: false,
          label: 'W/L',
          tooltip: 'Win/Loss',
          sort: 'higher',
        },
        conf_record: {
          id: 'conf_record',
          numeric: false,
          label: 'CR',
          tooltip: 'Conference Record Win/Loss',
          sort: 'higher',
        },
        neutralwins: {
          id: 'neutralwins',
          numeric: true,
          label: 'Neut. wins',
          tooltip: 'Neutral wins',
          sort: 'higher',
        },
        neutrallosses: {
          id: 'neutrallosses',
          numeric: true,
          label: 'Neut. losses',
          tooltip: 'Neutral losses',
          sort: 'lower',
        },
        homewins: {
          id: 'homewins',
          numeric: true,
          label: 'Home wins',
          tooltip: 'Home wins',
          sort: 'higher',
        },
        homelosses: {
          id: 'homelosses',
          numeric: true,
          label: 'Home losses',
          tooltip: 'Home losses',
          sort: 'lower',
        },
        roadwins: {
          id: 'roadwins',
          numeric: true,
          label: 'Road wins',
          tooltip: 'Road wins',
          sort: 'higher',
        },
        roadlosses: {
          id: 'roadlosses',
          numeric: true,
          label: 'Road losses',
          tooltip: 'Road losses',
          sort: 'lower',
        },
        streak: {
          id: 'streak',
          numeric: true,
          label: 'Streak',
          tooltip: 'Number of wins or losses in a row (negative for loss)',
          sort: 'higher',
        },
        win_margin: {
          id: 'win_margin',
          numeric: true,
          label: 'Win margin',
          tooltip: 'Win margin',
          sort: 'higher',
        },
        loss_margin: {
          id: 'loss_margin',
          numeric: true,
          label: 'Loss margin',
          tooltip: 'Loss margin',
          sort: 'lower',
        },
        confwin_margin: {
          id: 'confwin_margin',
          numeric: true,
          label: 'C Win margin',
          tooltip: 'Conference Win margin',
          sort: 'higher',
        },
        confloss_margin: {
          id: 'confloss_margin',
          numeric: true,
          label: 'C Loss margin',
          tooltip: 'Conference Loss margin',
          sort: 'lower',
        },
        elo: {
          id: 'elo',
          numeric: true,
          label: 'SR',
          tooltip: 'srating.io ELO rating',
          sort: 'higher',
        },
        elo_sos: {
          id: 'elo_sos',
          numeric: true,
          label: 'eSOS',
          tooltip: 'Strength of schedule (opponent elo)',
          sort: 'higher',
        },
        yards_per_play: {
          id: 'yards_per_play',
          numeric: true,
          label: 'YPP',
          tooltip: 'Yards per play',
          sort: 'higher',
        },
        points_per_play: {
          id: 'points_per_play',
          numeric: true,
          label: 'PPP',
          tooltip: 'Points per play',
          sort: 'higher',
        },
        // successful_pass_plays: {
        //   id: 'successful_pass_plays',
        //   numeric: true,
        //   label: 'SPP',
        //   tooltip: 'Successful pass plays',
        //   sort: 'higher',
        // },
        // successful_rush_plays: {
        //   id: 'successful_rush_plays',
        //   numeric: true,
        //   label: 'SRP',
        //   tooltip: 'Successful rush plays',
        //   sort: 'higher',
        // },
        // offensive_dvoa: {
        //   id: 'offensive_dvoa',
        //   numeric: true,
        //   label: 'O-DVOA',
        //   tooltip: 'offensive_dvoa', // todo
        //   sort: 'higher',
        // },
        // defensive_dvoa: {
        //   id: 'defensive_dvoa',
        //   numeric: true,
        //   label: 'D-DVOA',
        //   tooltip: 'defensive_dvoa', // todo
        //   sort: 'higher', // todo
        // },
        // first_downs: {
        //   id: 'first_downs',
        //   numeric: true,
        //   label: '1st downs',
        //   tooltip: '1st downs',
        //   sort: 'higher',
        // },
        // third_down_conversions: {
        //   id: 'third_down_conversions',
        //   numeric: true,
        //   label: '3rd down conv.',
        //   tooltip: '3rd down conversion',
        //   sort: 'higher',
        // },
        // third_down_attempts: {
        //   id: 'third_down_attempts',
        //   numeric: true,
        //   label: '3rd down att.',
        //   tooltip: '3rd down attempts',
        //   sort: 'higher',
        // },
        // fourth_down_conversions: {
        //   id: 'fourth_down_conversions',
        //   numeric: true,
        //   label: '4rd down conv.',
        //   tooltip: '4rd down conversion',
        //   sort: 'higher',
        // },
        // fourth_down_attempts: {
        //   id: 'fourth_down_attempts',
        //   numeric: true,
        //   label: '4rd down att.',
        //   tooltip: '4rd down attempts',
        //   sort: 'higher',
        // },
        // time_of_possession_seconds: {
        //   id: 'time_of_possession_seconds',
        //   numeric: true,
        //   label: 'ToP',
        //   tooltip: 'Time of possession in seconds',
        //   sort: 'higher',
        // },
        opponent_points: {
          id: 'opponent_points',
          numeric: true,
          label: 'Opp. PTS',
          tooltip: 'Opponent points',
          sort: 'higher',
        },
        opponent_yards_per_play: {
          id: 'opponent_yards_per_play',
          numeric: true,
          label: 'Opp. YPP',
          tooltip: 'Opponent Yards per play',
          sort: 'higher',
        },
        opponent_points_per_play: {
          id: 'opponent_points_per_play',
          numeric: true,
          label: 'Opp. PPP',
          tooltip: 'Opponent Points per play',
          sort: 'higher',
        },
        // opponent_successful_pass_plays: {
        //   id: 'opponent_successful_pass_plays',
        //   numeric: true,
        //   label: 'Opp. SPP',
        //   tooltip: 'Opponent Successful pass plays',
        //   sort: 'higher',
        // },
        // opponent_successful_rush_plays: {
        //   id: 'opponent_successful_rush_plays',
        //   numeric: true,
        //   label: 'Opp. SRP',
        //   tooltip: 'Opponent Successful rush plays',
        //   sort: 'higher',
        // },
        // opponent_offensive_dvoa: {
        //   id: 'opponent_offensive_dvoa',
        //   numeric: true,
        //   label: 'Opp. O-DVOA',
        //   tooltip: 'Opponent offensive_dvoa', // todo
        //   sort: 'higher',
        // },
        // opponent_defensive_dvoa: {
        //   id: 'opponent_defensive_dvoa',
        //   numeric: true,
        //   label: 'Opp. D-DVOA',
        //   tooltip: 'Opponent defensive_dvoa', // todo
        //   sort: 'higher', // todo
        // },
        // opponent_first_downs: {
        //   id: 'opponent_first_downs',
        //   numeric: true,
        //   label: 'Opp. 1st downs',
        //   tooltip: 'Opponent 1st downs',
        //   sort: 'higher',
        // },
        // opponent_third_down_conversions: {
        //   id: 'opponent_third_down_conversions',
        //   numeric: true,
        //   label: 'Opp. 3rd down conv.',
        //   tooltip: 'Opponent 3rd down conversion',
        //   sort: 'higher',
        // },
        // opponent_third_down_attempts: {
        //   id: 'opponent_third_down_attempts',
        //   numeric: true,
        //   label: 'Opp. 3rd down att.',
        //   tooltip: 'Opponent 3rd down attempts',
        //   sort: 'higher',
        // },
        // opponent_fourth_down_conversions: {
        //   id: 'opponent_fourth_down_conversions',
        //   numeric: true,
        //   label: 'Opp. 4rd down conv.',
        //   tooltip: 'Opponent 4rd down conversion',
        //   sort: 'higher',
        // },
        // opponent_fourth_down_attempts: {
        //   id: 'opponent_fourth_down_attempts',
        //   numeric: true,
        //   label: 'Opp. 4rd down att.',
        //   tooltip: 'Opponent 4rd down attempts',
        //   sort: 'higher',
        // },
        // opponent_time_of_possession_seconds: {
        //   id: 'opponent_time_of_possession_seconds',
        //   numeric: true,
        //   label: 'Opp. ToP',
        //   tooltip: 'Opponent Time of possession in seconds',
        //   sort: 'higher',
        // },
        opponent_passing_attempts: {
          id: 'opponent_passing_attempts',
          numeric: true,
          label: 'Opp. Pass att.',
          tooltip: 'Opponent Passing attempts',
          sort: 'higher',
        },
        opponent_passing_completions: {
          id: 'opponent_passing_completions',
          numeric: true,
          label: 'Opp. Pass comp.',
          tooltip: 'Opponent Passing completions',
          sort: 'higher',
        },
        opponent_passing_yards: {
          id: 'opponent_passing_yards',
          numeric: true,
          label: 'Opp. Pass yards',
          tooltip: 'Opponent Passing yards',
          sort: 'higher',
        },
        opponent_passing_completion_percentage: {
          id: 'opponent_passing_completion_percentage',
          numeric: true,
          label: 'Opp. Pass comp. %',
          tooltip: 'Opponent Passing completions percentage',
          sort: 'higher',
        },
        opponent_passing_yards_per_attempt: {
          id: 'opponent_passing_yards_per_attempt',
          numeric: true,
          label: 'Opp. Pass yards per att.',
          tooltip: 'Opponent Passing yard per attempt',
          sort: 'higher',
        },
        opponent_passing_yards_per_completion: {
          id: 'opponent_passing_yards_per_completion',
          numeric: true,
          label: 'Opp. Pass yards per comp.',
          tooltip: 'Opponent Passing yards per completion',
          sort: 'higher',
        },
        opponent_passing_touchdowns: {
          id: 'opponent_passing_touchdowns',
          numeric: true,
          label: 'Opp. Pass TD',
          tooltip: 'Opponent Passing touchdowns',
          sort: 'higher',
        },
        opponent_passing_interceptions: {
          id: 'opponent_passing_interceptions',
          numeric: true,
          label: 'Opp. Pass int.',
          tooltip: 'Opponent Passing interceptions',
          sort: 'higher',
        },
        opponent_passing_rating_pro: {
          id: 'opponent_passing_rating_pro',
          numeric: true,
          label: 'Opp. QBR(p)',
          tooltip: 'Opponent Quarter back rating (pro)',
          sort: 'higher',
        },
        opponent_passing_rating_college: {
          id: 'opponent_passing_rating_college',
          numeric: true,
          label: 'Opp. QBR(c)',
          tooltip: 'Opponent Quarter back rating (college)',
          sort: 'higher',
        },
        opponent_passing_long: {
          id: 'opponent_passing_long',
          numeric: true,
          label: 'Opp. Pass long',
          tooltip: 'Opponent Passing long',
          sort: 'higher',
        },
        opponent_rushing_attempts: {
          id: 'opponent_rushing_attempts',
          numeric: true,
          label: 'Opp. Rush att.',
          tooltip: 'Opponent Rushing attempts',
          sort: 'higher',
        },
        opponent_rushing_yards: {
          id: 'opponent_rushing_yards',
          numeric: true,
          label: 'Opp. Rush yards',
          tooltip: 'Opponent Rushing yards',
          sort: 'higher',
        },
        opponent_rushing_yards_per_attempt: {
          id: 'opponent_rushing_yards_per_attempt',
          numeric: true,
          label: 'Opp. Rush yards per att.',
          tooltip: 'Opponent Rushing yards per attempt',
          sort: 'higher',
        },
        opponent_rushing_touchdowns: {
          id: 'opponent_rushing_touchdowns',
          numeric: true,
          label: 'Opp. Rush TD',
          tooltip: 'Opponent Rushing touchdowns',
          sort: 'higher',
        },
        opponent_rushing_long: {
          id: 'opponent_rushing_long',
          numeric: true,
          label: 'Opp. Rush long',
          tooltip: 'Opponent Rushing long',
          sort: 'higher',
        },
        opponent_receptions: {
          id: 'opponent_receptions',
          numeric: true,
          label: 'Opp. Receptions',
          tooltip: 'Opponent # of receptions',
          sort: 'higher',
        },
        opponent_receiving_yards: {
          id: 'opponent_receiving_yards',
          numeric: true,
          label: 'Opp. Rec. yards',
          tooltip: 'Opponent Recieving yards',
          sort: 'higher',
        },
        opponent_receiving_yards_per_reception: {
          id: 'opponent_receiving_yards_per_reception',
          numeric: true,
          label: 'Opp. Rec. yards per recep.',
          tooltip: 'Opponent Receiving yards per reception',
          sort: 'higher',
        },
        opponent_receiving_touchdowns: {
          id: 'opponent_receiving_touchdowns',
          numeric: true,
          label: 'Opp. Rec. TD',
          tooltip: 'Opponent Receiving touchdowns',
          sort: 'higher',
        },
        opponent_receiving_long: {
          id: 'opponent_receiving_long',
          numeric: true,
          label: 'Opp. Rec. long',
          tooltip: 'Opponent Receiving long',
          sort: 'higher',
        },
        // opponent_punt_returns: {
        //   id: 'opponent_punt_returns',
        //   numeric: true,
        //   label: 'Opp. Punt ret.',
        //   tooltip: 'Opponent Punt returns',
        //   sort: 'higher',
        // },
        // opponent_punt_return_yards: {
        //   id: 'opponent_punt_return_yards',
        //   numeric: true,
        //   label: 'Opp. Punt ret. yards',
        //   tooltip: 'Opponent Punt return yards',
        //   sort: 'higher',
        // },
        // opponent_punt_return_yards_per_attempt: {
        //   id: 'opponent_punt_return_yards_per_attempt',
        //   numeric: true,
        //   label: 'Opp. Punt ret. yards per att.',
        //   tooltip: 'Opponent Punt return yards per attempt',
        //   sort: 'higher',
        // },
        // opponent_punt_return_touchdowns: {
        //   id: 'opponent_punt_return_touchdowns',
        //   numeric: true,
        //   label: 'Opp. Punt ret. TD',
        //   tooltip: 'Opponent Punt return touchdowns',
        //   sort: 'higher',
        // },
        // opponent_punt_return_long: {
        //   id: 'opponent_punt_return_long',
        //   numeric: true,
        //   label: 'Opp. Punt ret. long',
        //   tooltip: 'Opponent Punt return long',
        //   sort: 'higher',
        // },
        // opponent_kick_returns: {
        //   id: 'opponent_kick_returns',
        //   numeric: true,
        //   label: 'Opp. Kick ret.',
        //   tooltip: 'Opponent Kick returns',
        //   sort: 'higher',
        // },
        // opponent_kick_return_yards: {
        //   id: 'opponent_kick_return_yards',
        //   numeric: true,
        //   label: 'Opp. Kick ret. yards',
        //   tooltip: 'Opponent Kick return yards',
        //   sort: 'higher',
        // },
        // opponent_kick_return_yards_per_attempt: {
        //   id: 'opponent_kick_return_yards_per_attempt',
        //   numeric: true,
        //   label: 'Opp. Kick ret. yards per att.',
        //   tooltip: 'Opponent Kick return yards per attempt',
        //   sort: 'higher',
        // },
        // opponent_kick_return_touchdowns: {
        //   id: 'opponent_kick_return_touchdowns',
        //   numeric: true,
        //   label: 'Opp. Kick ret. TD',
        //   tooltip: 'Opponent Kick return touchdowns',
        //   sort: 'higher',
        // },
        // opponent_kick_return_long: {
        //   id: 'opponent_kick_return_long',
        //   numeric: true,
        //   label: 'Opp. Kick ret. long',
        //   tooltip: 'Opponent Kick return long',
        //   sort: 'higher',
        // },
        // opponent_punts: {
        //   id: 'opponent_punts',
        //   numeric: true,
        //   label: 'Opp. Punts',
        //   tooltip: 'Opponent Punts',
        //   sort: 'higher',
        // },
        // opponent_punt_yards: {
        //   id: 'opponent_punt_yards',
        //   numeric: true,
        //   label: 'Opp. Punt yards',
        //   tooltip: 'Opponent Punt yards',
        //   sort: 'higher',
        // },
        // opponent_punt_average: {
        //   id: 'opponent_punt_average',
        //   numeric: true,
        //   label: 'Opp. Punt avg.',
        //   tooltip: 'Opponent Punt average',
        //   sort: 'higher',
        // },
        // opponent_punt_long: {
        //   id: 'opponent_punt_long',
        //   numeric: true,
        //   label: 'Opp. Punt long',
        //   tooltip: 'Opponent Punt long',
        //   sort: 'higher',
        // },
        // opponent_field_goals_attempted: {
        //   id: 'opponent_field_goals_attempted',
        //   numeric: true,
        //   label: 'Opp. FG att.',
        //   tooltip: 'Opponent Field goals attempted',
        //   sort: 'higher',
        // },
        // opponent_field_goals_made: {
        //   id: 'opponent_field_goals_made',
        //   numeric: true,
        //   label: 'Opp. FGs',
        //   tooltip: 'Opponent Field goals made',
        //   sort: 'higher',
        // },
        // opponent_field_goal_percentage: {
        //   id: 'opponent_field_goal_percentage',
        //   numeric: true,
        //   label: 'Opp. FG%',
        //   tooltip: 'Opponent Field goal percentage',
        //   sort: 'higher',
        // },
        // opponent_field_goals_longest_made: {
        //   id: 'opponent_field_goals_longest_made',
        //   numeric: true,
        //   label: 'Opp. FG long',
        //   tooltip: 'Opponent Field goal longest made',
        //   sort: 'higher',
        // },
        // opponent_extra_points_attempted: {
        //   id: 'opponent_extra_points_attempted',
        //   numeric: true,
        //   label: 'Opp. 2pt att.',
        //   tooltip: 'Opponent 2pt conversion attempts',
        //   sort: 'higher',
        // },
        // opponent_extra_points_made: {
        //   id: 'opponent_extra_points_made',
        //   numeric: true,
        //   label: 'Opp. 2pt con.',
        //   tooltip: 'Opponent 2pt conversions',
        //   sort: 'higher',
        // },
        // opponent_interceptions: {
        //   id: 'opponent_interceptions',
        //   numeric: true,
        //   label: 'Opp. Int.',
        //   tooltip: 'Opponent Interceptions',
        //   sort: 'higher',
        // },
        // opponent_interception_return_yards: {
        //   id: 'opponent_interception_return_yards',
        //   numeric: true,
        //   label: 'Opp. Int. ret. yards',
        //   tooltip: 'Opponent Interceptions return yards',
        //   sort: 'higher',
        // },
        // opponent_interception_return_touchdowns: {
        //   id: 'opponent_interception_return_touchdowns',
        //   numeric: true,
        //   label: 'Opp. Int. ret. TD',
        //   tooltip: 'Opponent Interceptions return touchdowns',
        //   sort: 'higher',
        // },
        // opponent_solo_tackles: {
        //   id: 'opponent_solo_tackles',
        //   numeric: true,
        //   label: 'Opp. Solo tackle',
        //   tooltip: 'Opponent Solo tackles',
        //   sort: 'higher',
        // },
        // opponent_assisted_tackles: {
        //   id: 'opponent_assisted_tackles',
        //   numeric: true,
        //   label: 'Opp. Ast. tackle',
        //   tooltip: 'Opponent Assisted tackles',
        //   sort: 'higher',
        // },
        // opponent_tackles_for_loss: {
        //   id: 'opponent_tackles_for_loss',
        //   numeric: true,
        //   label: 'Opp. Tackle for loss',
        //   tooltip: 'Opponent Tackles for loss',
        //   sort: 'higher',
        // },
        // opponent_sacks: {
        //   id: 'opponent_sacks',
        //   numeric: true,
        //   label: 'Opp. Sacks',
        //   tooltip: 'Opponent Sacks',
        //   sort: 'higher',
        // },
        // opponent_passes_defended: {
        //   id: 'opponent_passes_defended',
        //   numeric: true,
        //   label: 'Opp. Pass defended',
        //   tooltip: 'Opponent Passes defended',
        //   sort: 'higher',
        // },
        // opponent_fumbles_recovered: {
        //   id: 'opponent_fumbles_recovered',
        //   numeric: true,
        //   label: 'Opp. Fumble rec.',
        //   tooltip: 'Opponent Fumbles recovered',
        //   sort: 'higher',
        // },
        // opponent_fumble_return_touchdowns: {
        //   id: 'opponent_fumble_return_touchdowns',
        //   numeric: true,
        //   label: 'Opp. Fumble ret. TD',
        //   tooltip: 'Opponent Fumbles returned to touchdown',
        //   sort: 'higher',
        // },
        // opponent_quarterback_hurries: {
        //   id: 'opponent_quarterback_hurries',
        //   numeric: true,
        //   label: 'Opp. QB hurry',
        //   tooltip: 'Opponent QB hurries',
        //   sort: 'higher',
        // },
        // opponent_fumbles: {
        //   id: 'opponent_fumbles',
        //   numeric: true,
        //   label: 'Opp. Fumbles',
        //   tooltip: 'Opponent Fumbles',
        //   sort: 'lower',
        // },
        // opponent_fumbles_lost: {
        //   id: 'opponent_fumbles_lost',
        //   numeric: true,
        //   label: 'Opp. Fumbles lost',
        //   tooltip: 'Opponent Fumbles lost',
        //   sort: 'lower',
        // },
      });
    }
    if (view === 'player') {
      Object.assign(headCells, {
        team_name: {
          id: 'team_name',
          numeric: false,
          label: 'Team',
          tooltip: 'Team name',
        },
        games: {
          id: 'games',
          numeric: false,
          label: 'G',
          tooltip: 'Games played',
        },
        position: {
          id: 'position',
          numeric: false,
          label: 'Position',
          tooltip: 'Player position',
        },
        number: {
          id: 'number',
          numeric: false,
          label: 'Number',
          tooltip: 'Jersey number',
        },
        height: {
          id: 'height',
          numeric: false,
          label: 'Height',
          tooltip: 'Player height',
        },
        // minutes_played: {
        //   id: 'minutes_played',
        //   numeric: true,
        //   label: 'MP',
        //   tooltip: 'Total minutes played',
        //   sort: 'higher',
        // },
        // minutes_per_game: {
        //   id: 'minutes_per_game',
        //   numeric: true,
        //   label: 'MPG',
        //   tooltip: 'Minutes played per game',
        //   sort: 'higher',
        // },
        points_per_game: {
          id: 'points_per_game',
          numeric: true,
          label: 'PPG',
          tooltip: 'Points per game',
          sort: 'higher',
        },
        passing_attempts_per_game: {
          id: 'passing_attempts_per_game',
          numeric: true,
          label: 'Pass att. per game',
          tooltip: 'Passing attempts per game',
          sort: 'higher',
        },
        passing_completions_per_game: {
          id: 'passing_completions_per_game',
          numeric: true,
          label: 'Pass comp. per game',
          tooltip: 'Passing completions per game',
          sort: 'higher',
        },
        passing_yards_per_game: {
          id: 'passing_yards_per_game',
          numeric: true,
          label: 'Pass yards per game',
          tooltip: 'Passing yards per game',
          sort: 'higher',
        },
        passing_touchdowns_per_game: {
          id: 'passing_touchdowns_per_game',
          numeric: true,
          label: 'Pass TD per game',
          tooltip: 'Passing touchdowns per game',
          sort: 'higher',
        },
        passing_interceptions_per_game: {
          id: 'passing_interceptions_per_game',
          numeric: true,
          label: 'Pass int. per game',
          tooltip: 'Passing interceptions per game',
          sort: 'higher',
        },
        rushing_attempts_per_game: {
          id: 'rushing_attempts_per_game',
          numeric: true,
          label: 'Rush att. per game',
          tooltip: 'Rushing attempts per game',
          sort: 'higher',
        },
        rushing_yards_per_game: {
          id: 'rushing_yards_per_game',
          numeric: true,
          label: 'Rush yards per game',
          tooltip: 'Rushing yards per game',
          sort: 'higher',
        },
        rushing_touchdowns_per_game: {
          id: 'rushing_touchdowns_per_game',
          numeric: true,
          label: 'Rush TD per game',
          tooltip: 'Rushing touchdowns per game',
          sort: 'higher',
        },
        receptions_per_game: {
          id: 'receptions_per_game',
          numeric: true,
          label: 'Receptions per game',
          tooltip: '# of receptions per game',
          sort: 'higher',
        },
        receiving_yards_per_game: {
          id: 'receiving_yards_per_game',
          numeric: true,
          label: 'Rec. yards per game',
          tooltip: 'Recieving yards per game',
          sort: 'higher',
        },
        receiving_touchdowns_per_game: {
          id: 'receiving_touchdowns_per_game',
          numeric: true,
          label: 'Rec. TD per game',
          tooltip: 'Receiving touchdowns per game',
          sort: 'higher',
        },
        punt_returns_per_game: {
          id: 'punt_returns_per_game',
          numeric: true,
          label: 'Punt ret. per game',
          tooltip: 'Punt returns per game',
          sort: 'higher',
        },
        punt_return_yards_per_game: {
          id: 'punt_return_yards_per_game',
          numeric: true,
          label: 'Punt ret. yards per game',
          tooltip: 'Punt return yards per game',
          sort: 'higher',
        },
        punt_return_touchdowns_per_game: {
          id: 'punt_return_touchdowns_per_game',
          numeric: true,
          label: 'Punt ret. TD per game',
          tooltip: 'Punt return touchdowns per game',
          sort: 'higher',
        },
        kick_returns_per_game: {
          id: 'kick_returns_per_game',
          numeric: true,
          label: 'Kick ret. per game',
          tooltip: 'Kick returns per game',
          sort: 'higher',
        },
        kick_return_yards_per_game: {
          id: 'kick_return_yards_per_game',
          numeric: true,
          label: 'Kick ret. yards per game',
          tooltip: 'Kick return yards per game',
          sort: 'higher',
        },
        kick_return_touchdowns_per_game: {
          id: 'kick_return_touchdowns_per_game',
          numeric: true,
          label: 'Kick ret. TD per game',
          tooltip: 'Kick return touchdowns per game',
          sort: 'higher',
        },
        punts_per_game: {
          id: 'punts_per_game',
          numeric: true,
          label: 'Punts per game',
          tooltip: 'Punts per game',
          sort: 'higher',
        },
        punt_yards_per_game: {
          id: 'punt_yards_per_game',
          numeric: true,
          label: 'Punt yards per game',
          tooltip: 'Punt yards per game',
          sort: 'higher',
        },
        field_goals_attempted_per_game: {
          id: 'field_goals_attempted_per_game',
          numeric: true,
          label: 'FG att. per game',
          tooltip: 'Field goals attempted per game',
          sort: 'higher',
        },
        field_goals_made_per_game: {
          id: 'field_goals_made_per_game',
          numeric: true,
          label: 'FGs per game',
          tooltip: 'Field goals made per game',
          sort: 'higher',
        },
        interceptions_per_game: {
          id: 'interceptions_per_game',
          numeric: true,
          label: 'Int. per game',
          tooltip: 'Interceptions per game',
          sort: 'higher',
        },
        sacks_per_game: {
          id: 'sacks_per_game',
          numeric: true,
          label: 'Sacks per game',
          tooltip: 'Sacks per game',
          sort: 'higher',
        },
        fumbles_per_game: {
          id: 'fumbles_per_game',
          numeric: true,
          label: 'Fumbles per game',
          tooltip: 'Fumbles per game',
          sort: 'lower',
        },
      });
    }
  }

  if (view === 'coach') {
    Object.assign(headCells, {
      team_name: {
        id: 'team_name',
        numeric: false,
        label: 'Team',
        tooltip: 'Team name',
      },
      games: {
        id: 'games',
        numeric: true,
        label: 'G',
        tooltip: 'Total games',
        sort: 'higher',
      },
      elo: {
        id: 'elo',
        numeric: true,
        label: 'SR',
        tooltip: 'srating.io ELO rating',
        sort: 'higher',
      },
      wins: {
        id: 'wins',
        numeric: false,
        label: 'W',
        tooltip: 'Total Wins',
        sort: 'higher',
      },
      losses: {
        id: 'losses',
        numeric: false,
        label: 'L',
        tooltip: 'Total Losses',
        sort: 'lower',
      },
      confwins: {
        id: 'confwins',
        numeric: false,
        label: 'CONF W',
        tooltip: 'Conference Total Wins',
        sort: 'higher',
      },
      conflosses: {
        id: 'conflosses',
        numeric: false,
        label: 'CONF L',
        tooltip: 'Conference Total Losses',
        sort: 'lower',
      },
      nonconfwins: {
        id: 'nonconfwins',
        numeric: false,
        label: 'NONC W',
        tooltip: 'Non-Conference Total Wins',
        sort: 'higher',
      },
      nonconflosses: {
        id: 'nonconflosses',
        numeric: false,
        label: 'NONC L',
        tooltip: 'Non-Conference Total Losses',
        sort: 'lower',
      },
      neutralwins: {
        id: 'neutralwins',
        numeric: true,
        label: 'Neut. wins',
        tooltip: 'Neutral wins',
        sort: 'higher',
      },
      neutrallosses: {
        id: 'neutrallosses',
        numeric: true,
        label: 'Neut. losses',
        tooltip: 'Neutral losses',
        sort: 'lower',
      },
      homewins: {
        id: 'homewins',
        numeric: true,
        label: 'Home wins',
        tooltip: 'Home wins',
        sort: 'higher',
      },
      homelosses: {
        id: 'homelosses',
        numeric: true,
        label: 'Home losses',
        tooltip: 'Home losses',
        sort: 'lower',
      },
      roadwins: {
        id: 'roadwins',
        numeric: true,
        label: 'Road wins',
        tooltip: 'Road wins',
        sort: 'higher',
      },
      roadlosses: {
        id: 'roadlosses',
        numeric: true,
        label: 'Road losses',
        tooltip: 'Road losses',
        sort: 'lower',
      },
      elo_sos: {
        id: 'elo_sos',
        numeric: true,
        label: 'eSOS',
        tooltip: 'Strength of schedule (opponent elo)',
        sort: 'higher',
      },
      win_percentage: {
        id: 'win_percentage',
        numeric: true,
        label: 'W%',
        tooltip: 'Win percentage',
        sort: 'higher',
      },
      conf_win_percentage: {
        id: 'conf_win_percentage',
        numeric: true,
        label: 'C%',
        tooltip: 'Conference win percentage',
        sort: 'higher',
      },
      nonconf_win_percentage: {
        id: 'non_conf_win_percentage',
        numeric: true,
        label: 'NON C%',
        tooltip: 'Non-Conference win percentage',
        sort: 'higher',
      },
      home_win_percentage: {
        id: 'home_win_percentage',
        numeric: true,
        label: 'H%',
        tooltip: 'Home win percentage',
        sort: 'higher',
      },
      road_win_percentage: {
        id: 'road_win_percentage',
        numeric: true,
        label: 'R%',
        tooltip: 'Road win percentage',
        sort: 'higher',
      },
      neutral_win_percentage: {
        id: 'neutral_win_percentage',
        numeric: true,
        label: 'N%',
        tooltip: 'Neutral win percentage',
        sort: 'higher',
      },
    });
  }

  return headCells;
};

export const getViewableColumns = ({ organization_id, view, columnView, customColumns }) => {
  if (columnView === 'custom') {
    return customColumns;
  }

  if (organization_id === Organization.getCBBID()) {
    if (columnView === 'composite') {
      if (view === 'team') {
        return ['rank', 'name', 'wins', 'conf_record', 'elo', 'adjusted_efficiency_rating', 'elo_sos', 'offensive_rating', 'defensive_rating', 'opponent_efficiency_rating', 'streak', 'conference_code'];
      }
      if (view === 'player') {
        return ['rank', 'name', 'team_name', 'efficiency_rating', 'offensive_rating', 'defensive_rating', 'player_efficiency_rating', 'minutes_per_game', 'points_per_game', 'usage_percentage', 'true_shooting_percentage'];
      }
      if (view === 'conference') {
        return ['rank', 'name', 'adjusted_efficiency_rating', 'elo', 'elo_sos', 'opponent_efficiency_rating', 'offensive_rating', 'defensive_rating', 'nonconfwins'];
      }
      if (view === 'transfer') {
        return ['rank', 'name', 'team_name', 'committed_team_name', 'efficiency_rating', 'offensive_rating', 'defensive_rating', 'player_efficiency_rating', 'minutes_per_game', 'points_per_game', 'usage_percentage', 'true_shooting_percentage'];
      }
      if (view === 'coach') {
        return [
          'rank',
          'name',
          'team_name',
          'elo',
          'elo_sos',
          'games',
          'win_percentage',
          'conf_win_percentage',
          'nonconf_win_percentage',
          'home_win_percentage',
          'road_win_percentage',
          'neutral_win_percentage',
        ];
      }
    } else if (columnView === 'offense') {
      if (view === 'team') {
        return ['rank', 'name', 'offensive_rating', 'points', 'field_goal_percentage', 'two_point_field_goal_percentage', 'three_point_field_goal_percentage', 'free_throw_percentage', 'offensive_rebounds', 'assists', 'turnovers', 'possessions', 'pace'];
      }
      if (view === 'player' || view === 'transfer') {
        return ['rank', 'name', 'offensive_rating', 'points_per_game', 'field_goal_percentage', 'two_point_field_goal_percentage', 'three_point_field_goal_percentage', 'free_throw_percentage', 'offensive_rebounds_per_game', 'assists_per_game', 'turnovers_per_game', 'turnover_percentage'];
      }
      if (view === 'conference') {
        return ['rank', 'name', 'offensive_rating', 'points', 'field_goal_percentage', 'two_point_field_goal_percentage', 'three_point_field_goal_percentage', 'free_throw_percentage', 'offensive_rebounds', 'assists', 'turnovers', 'possessions', 'pace'];
      }
    } else if (columnView === 'defense') {
      if (view === 'team') {
        return ['rank', 'name', 'defensive_rating', 'defensive_rebounds', 'steals', 'blocks', 'opponent_points', 'opponent_field_goal_percentage', 'opponent_two_point_field_goal_percentage', 'opponent_three_point_field_goal_percentage', 'fouls'];
      }
      if (view === 'player' || view === 'transfer') {
        return ['rank', 'name', 'defensive_rating', 'defensive_rebounds_per_game', 'steals_per_game', 'blocks_per_game', 'fouls_per_game', 'defensive_rebound_percentage', 'steal_percentage', 'block_percentage'];
      }
      if (view === 'conference') {
        return ['rank', 'name', 'defensive_rating', 'defensive_rebounds', 'steals', 'blocks', 'opponent_points', 'opponent_field_goal_percentage', 'opponent_two_point_field_goal_percentage', 'opponent_three_point_field_goal_percentage', 'fouls'];
      }
    }
  }

  if (organization_id === Organization.getCFBID()) {
    if (columnView === 'composite') {
      if (view === 'team') {
        return ['rank', 'name', 'wins', 'conf_record', 'elo', 'passing_rating_college', 'points', 'yards_per_play', 'points_per_play', 'elo_sos', 'conference_code'];
      }
      if (view === 'player') {
        return ['rank', 'name', 'team_name', 'passing_rating_college'];
      }
      if (view === 'conference') {
        return ['rank', 'name', 'elo', 'wins', 'passing_rating_college', 'points', 'yards_per_play', 'points_per_play'];
      }
      if (view === 'coach') {
        return [
          'rank',
          'name',
          'team_name',
          'elo',
          'elo_sos',
          'games',
          'win_percentage',
          'conf_win_percentage',
          'nonconf_win_percentage',
          'home_win_percentage',
          'road_win_percentage',
          'neutral_win_percentage',
        ];
      }
    } else if (columnView === 'passing') {
      if (view === 'team' || view === 'player' || view === 'conference') {
        return ['rank', 'name', 'passing_rating_college', 'passing_rating_pro', 'passing_attempts', 'passing_completions', 'passing_yards', 'passing_completion_percentage', 'passing_yards_per_attempt', 'passing_yards_per_completion', 'passing_touchdowns', 'passing_interceptions', 'passing_long'];
      }
    } else if (columnView === 'rushing') {
      if (view === 'team' || view === 'player' || view === 'conference') {
        return ['rank', 'name', 'rushing_attempts', 'rushing_yards', 'rushing_yards_per_attempt', 'rushing_touchdowns', 'rushing_long'];
      }
    } else if (columnView === 'recieving') {
      if (view === 'team' || view === 'player' || view === 'conference') {
        return ['rank', 'name', 'receptions', 'receiving_yards', 'receiving_yards_per_reception', 'receiving_touchdowns', 'receiving_long'];
      }
    }
  }

  return [];
};
